// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#ifndef _ESP32_TFT_THROTTLE_UI_H
#define _ESP32_TFT_THROTTLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Home.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_vthrottle_logo_png);   // assets/vthrottle_logo.png
LV_IMG_DECLARE( ui_img_turnout_xc_png);   // assets/turnout_xc.png
LV_IMG_DECLARE( ui_img_tunrout_xc1_png);   // assets/tunrout_xc1.png
LV_IMG_DECLARE( ui_img_turnout_tl0_0_png);   // assets/turnout_tl0_0.png
LV_IMG_DECLARE( ui_img_turnout_tl0_1_png);   // assets/turnout_tl0_1.png
LV_IMG_DECLARE( ui_img_turnout_tr0_1_png);   // assets/turnout_tr0_1.png
LV_IMG_DECLARE( ui_img_turnout_tl2_0_png);   // assets/turnout_tl2_0.png
LV_IMG_DECLARE( ui_img_turnout_tl2_1_png);   // assets/turnout_tl2_1.png
LV_IMG_DECLARE( ui_img_turnout_tr2_1_png);   // assets/turnout_tr2_1.png
LV_IMG_DECLARE( ui_img_loco_fwd_png);   // assets/loco_fwd.png
LV_IMG_DECLARE( ui_img_loco_rev_png);   // assets/loco_rev.png
LV_IMG_DECLARE( ui_img_horn_png);   // assets/horn.png
LV_IMG_DECLARE( ui_img_sound_wave_png);   // assets/sound_wave.png
LV_IMG_DECLARE( ui_img_sound_off_png);   // assets/sound_off.png
LV_IMG_DECLARE( ui_img_sound_png);   // assets/sound.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
