// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#ifndef _UI_COMP_THRCOMP_H
#define _UI_COMP_THRCOMP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ThrComp
#define UI_COMP_THRCOMP_THRCOMP 0
#define UI_COMP_THRCOMP_LOCOTHR 1
#define UI_COMP_THRCOMP_LOCOSPEED 2
#define UI_COMP_THRCOMP_LOCONAME 3
#define UI_COMP_THRCOMP_LOCOREV 4
#define UI_COMP_THRCOMP_HORN 5
#define UI_COMP_THRCOMP_FUNCBUTTON 6
#define UI_COMP_THRCOMP_FUNCBUTTON_FUNCLABEL 7
#define _UI_COMP_THRCOMP_NUM 8
lv_obj_t *ui_ThrComp_create(lv_obj_t *comp_parent);
void ui_event_comp_ThrComp_LocoThr( lv_event_t * e);
void ui_event_comp_ThrComp_LocoName( lv_event_t * e);
void ui_event_comp_ThrComp_LocoRev( lv_event_t * e);
void ui_event_comp_ThrComp_horn( lv_event_t * e);
void ui_event_comp_ThrComp_FuncButton( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
