// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#include "ui.h"

void ui_event_comp_ThrComp_LocoThr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoSpeed( e );
      _ui_slider_set_text_value( comp_ThrComp[UI_COMP_THRCOMP_LOCOSPEED], target, "", "");
}
}

void ui_event_comp_ThrComp_LocoName( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setThrottleLoco( e );
}
}

void ui_event_comp_ThrComp_LocoRev( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoReverse( e );
}
}

void ui_event_comp_ThrComp_horn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_PRESSED) {
      setLocoHorn( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      setLocoHorn( e );
}
}

void ui_event_comp_ThrComp_RouteBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( comp_ThrComp[UI_COMP_THRCOMP_ROUTEPANEL], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_comp_ThrComp_FuncButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( comp_ThrComp[UI_COMP_THRCOMP_FUNCPANEL], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      openLocoFunc( e );
}
}

void ui_event_comp_ThrComp_HeadLightF0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoFunc0( e );
}
}

void ui_event_comp_ThrComp_CouplerF3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc3( e );
}
}

void ui_event_comp_ThrComp_FlangeF7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc7( e );
}
}

void ui_event_comp_ThrComp_RadiatorF11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc11( e );
}
}

void ui_event_comp_ThrComp_MasterSoundF8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoFunc8( e );
}
}

void ui_event_comp_ThrComp_FuncPanelClose( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( comp_ThrComp[UI_COMP_THRCOMP_FUNCPANEL], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_comp_ThrComp_StartBlock( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoBlk( e );
}
}

void ui_event_comp_ThrComp_RouteStart( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      setRouteState( e );
}
}

void ui_event_comp_ThrComp_RouteClose( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( comp_ThrComp[UI_COMP_THRCOMP_ROUTEPANEL], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// COMPONENT ThrComp

lv_obj_t *ui_ThrComp_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ThrComp;
cui_ThrComp = lv_obj_create(comp_parent);
lv_obj_set_width( cui_ThrComp, 170);
lv_obj_set_height( cui_ThrComp, 210);
lv_obj_set_x( cui_ThrComp, -20 );
lv_obj_set_y( cui_ThrComp, -20 );
lv_obj_add_flag( cui_ThrComp, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( cui_ThrComp, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(cui_ThrComp, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_color(cui_ThrComp, lv_color_hex(0xE0DEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ThrComp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_ThrComp, lv_color_hex(0xE0DEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_ThrComp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoThr;
cui_LocoThr = lv_slider_create(cui_ThrComp);
lv_slider_set_range(cui_LocoThr, 0,128);
lv_slider_set_value( cui_LocoThr, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(cui_LocoThr)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( cui_LocoThr, 0, LV_ANIM_OFF);
lv_obj_set_width( cui_LocoThr, 15);
lv_obj_set_height( cui_LocoThr, 150);
lv_obj_set_x( cui_LocoThr, 40 );
lv_obj_set_y( cui_LocoThr, -20 );
lv_obj_set_align( cui_LocoThr, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(cui_LocoThr, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoThr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_LocoThr, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_LocoThr, lv_color_hex(0xC90000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoThr, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_LocoThr, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoThr, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_LocoThr, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_LocoThr, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_LocoThr, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoSpeed;
cui_LocoSpeed = lv_label_create(cui_ThrComp);
lv_obj_set_width( cui_LocoSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LocoSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LocoSpeed, 120 );
lv_obj_set_y( cui_LocoSpeed, -5 );
lv_label_set_text(cui_LocoSpeed,"0");
lv_obj_set_style_text_color(cui_LocoSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LocoSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_LocoSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LocoSpeed, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_LocoSpeed, lv_color_hex(0xF1F9D4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoName;
cui_LocoName = lv_dropdown_create(cui_ThrComp);
lv_dropdown_set_dir( cui_LocoName, LV_DIR_TOP);
lv_dropdown_set_options( cui_LocoName, "" );
lv_obj_set_width( cui_LocoName, 120);
lv_obj_set_height( cui_LocoName, 30);
lv_obj_set_x( cui_LocoName, -10 );
lv_obj_set_y( cui_LocoName, 88 );
lv_obj_set_align( cui_LocoName, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_LocoName, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_decor(cui_LocoName, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LocoName, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_LocoName, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_LocoName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_LocoName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_LocoName, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(cui_LocoName, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LocoName, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(cui_LocoName, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(cui_LocoName, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_LocoName, LV_TEXT_ALIGN_AUTO, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LocoName, &lv_font_montserrat_18, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(lv_dropdown_get_list(cui_LocoName), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(cui_LocoName), &lv_font_montserrat_12,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(lv_dropdown_get_list(cui_LocoName), LV_TEXT_ALIGN_CENTER,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(cui_LocoName), &lv_font_montserrat_12,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(cui_LocoName), lv_color_hex(0x70F9EB),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(cui_LocoName), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoRev;
cui_LocoRev = lv_imgbtn_create(cui_ThrComp);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_loco_rev_png, NULL);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_loco_rev_png, NULL);
lv_obj_set_width( cui_LocoRev, 40);
lv_obj_set_height( cui_LocoRev, 40);
lv_obj_set_x( cui_LocoRev, -1 );
lv_obj_set_y( cui_LocoRev, 74 );
lv_obj_add_flag( cui_LocoRev, LV_OBJ_FLAG_CHECKABLE );   /// Flags

lv_obj_t *cui_horn;
cui_horn = lv_imgbtn_create(cui_ThrComp);
lv_imgbtn_set_src(cui_horn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_horn_png, NULL);
lv_imgbtn_set_src(cui_horn, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sound_wave_png, NULL);
lv_obj_set_width( cui_horn, 32);
lv_obj_set_height( cui_horn, 32);
lv_obj_set_x( cui_horn, 2 );
lv_obj_set_y( cui_horn, 116 );
lv_obj_clear_flag( cui_horn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags

lv_obj_t *cui_RouteBtn;
cui_RouteBtn = lv_btn_create(cui_ThrComp);
lv_obj_set_width( cui_RouteBtn, 80);
lv_obj_set_height( cui_RouteBtn, 30);
lv_obj_set_x( cui_RouteBtn, -30 );
lv_obj_set_y( cui_RouteBtn, -33 );
lv_obj_set_align( cui_RouteBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_RouteBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_RouteBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_RouteBtn, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_RouteBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_RouteBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_RouteBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_RouteBtn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_RouteBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_RouteBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_RouteBtn, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_RouteBtn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_RouteLabel;
cui_RouteLabel = lv_label_create(cui_RouteBtn);
lv_obj_set_width( cui_RouteLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_RouteLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_RouteLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_RouteLabel,"Route");
lv_obj_set_style_text_color(cui_RouteLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_RouteLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_FuncButton;
cui_FuncButton = lv_btn_create(cui_ThrComp);
lv_obj_set_width( cui_FuncButton, 80);
lv_obj_set_height( cui_FuncButton, 30);
lv_obj_set_x( cui_FuncButton, -29 );
lv_obj_set_y( cui_FuncButton, -79 );
lv_obj_set_align( cui_FuncButton, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_FuncButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_FuncButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_FuncButton, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_FuncButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_FuncButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_FuncButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_FuncButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_FuncButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_FuncButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_FuncButton, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_FuncButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_FuncLabel;
cui_FuncLabel = lv_label_create(cui_FuncButton);
lv_obj_set_width( cui_FuncLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_FuncLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_FuncLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_FuncLabel,"Function");
lv_obj_set_style_text_color(cui_FuncLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_FuncLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_FuncPanel;
cui_FuncPanel = lv_obj_create(cui_ThrComp);
lv_obj_set_width( cui_FuncPanel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_FuncPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_FuncPanel, -157 );
lv_obj_set_y( cui_FuncPanel, -74 );
lv_obj_add_flag( cui_FuncPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( cui_FuncPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_FuncPanel, lv_color_hex(0xF8F482), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_FuncPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_FuncPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_FuncPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_FuncPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_FuncPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_FuncPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_FuncPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_FuncPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(cui_FuncPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(cui_FuncPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_HeadLightF0;
cui_HeadLightF0 = lv_btn_create(cui_FuncPanel);
lv_obj_set_width( cui_HeadLightF0, 80);
lv_obj_set_height( cui_HeadLightF0, 30);
lv_obj_set_x( cui_HeadLightF0, -10 );
lv_obj_set_y( cui_HeadLightF0, -10 );
lv_obj_add_flag( cui_HeadLightF0, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_HeadLightF0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_HeadLightF0, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_HeadLightF0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_HeadLightF0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_HeadLightF0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_HeadLightF0, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_HeadLightF0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_HeadLightF0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_HeadLightF0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_HeadLightF0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(cui_HeadLightF0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(cui_HeadLightF0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_HeadLightF0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_HeadLightF0, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_LabelF0;
cui_LabelF0 = lv_label_create(cui_HeadLightF0);
lv_obj_set_width( cui_LabelF0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelF0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LabelF0, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelF0,"Head Light");
lv_obj_set_style_text_color(cui_LabelF0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LabelF0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelF0, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_CouplerF3;
cui_CouplerF3 = lv_btn_create(cui_FuncPanel);
lv_obj_set_width( cui_CouplerF3, 80);
lv_obj_set_height( cui_CouplerF3, 30);
lv_obj_set_x( cui_CouplerF3, 80 );
lv_obj_set_y( cui_CouplerF3, -10 );
lv_obj_add_flag( cui_CouplerF3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_CouplerF3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_CouplerF3, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_CouplerF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_CouplerF3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_CouplerF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_CouplerF3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_CouplerF3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_CouplerF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_CouplerF3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_CouplerF3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(cui_CouplerF3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(cui_CouplerF3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelF3;
cui_LabelF3 = lv_label_create(cui_CouplerF3);
lv_obj_set_width( cui_LabelF3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelF3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LabelF3, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelF3,"Coupler");
lv_obj_set_style_text_color(cui_LabelF3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LabelF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelF3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_FlangeF7;
cui_FlangeF7 = lv_btn_create(cui_FuncPanel);
lv_obj_set_width( cui_FlangeF7, 80);
lv_obj_set_height( cui_FlangeF7, 30);
lv_obj_set_x( cui_FlangeF7, -10 );
lv_obj_set_y( cui_FlangeF7, 30 );
lv_obj_add_flag( cui_FlangeF7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_FlangeF7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_FlangeF7, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_FlangeF7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_FlangeF7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_FlangeF7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_FlangeF7, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_FlangeF7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_FlangeF7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_FlangeF7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_FlangeF7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(cui_FlangeF7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(cui_FlangeF7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelF7;
cui_LabelF7 = lv_label_create(cui_FlangeF7);
lv_obj_set_width( cui_LabelF7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelF7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LabelF7, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelF7,"Flange");
lv_obj_set_style_text_color(cui_LabelF7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LabelF7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelF7, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_RadiatorF11;
cui_RadiatorF11 = lv_btn_create(cui_FuncPanel);
lv_obj_set_width( cui_RadiatorF11, 80);
lv_obj_set_height( cui_RadiatorF11, 30);
lv_obj_set_x( cui_RadiatorF11, 80 );
lv_obj_set_y( cui_RadiatorF11, 30 );
lv_obj_add_flag( cui_RadiatorF11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_RadiatorF11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_RadiatorF11, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_RadiatorF11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_RadiatorF11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_RadiatorF11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_RadiatorF11, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_RadiatorF11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_RadiatorF11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_RadiatorF11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_RadiatorF11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(cui_RadiatorF11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(cui_RadiatorF11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelF11;
cui_LabelF11 = lv_label_create(cui_RadiatorF11);
lv_obj_set_width( cui_LabelF11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelF11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LabelF11, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelF11,"Radiator");
lv_obj_set_style_text_color(cui_LabelF11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LabelF11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelF11, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_MasterSoundF8;
cui_MasterSoundF8 = lv_imgbtn_create(cui_FuncPanel);
lv_imgbtn_set_src(cui_MasterSoundF8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sound_off_png, NULL);
lv_imgbtn_set_src(cui_MasterSoundF8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sound_png, NULL);
lv_imgbtn_set_src(cui_MasterSoundF8, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_sound_off_png, NULL);
lv_imgbtn_set_src(cui_MasterSoundF8, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_sound_png, NULL);
lv_obj_set_width( cui_MasterSoundF8, 30);
lv_obj_set_height( cui_MasterSoundF8, 30);
lv_obj_set_x( cui_MasterSoundF8, 3 );
lv_obj_set_y( cui_MasterSoundF8, 103 );
lv_obj_add_flag( cui_MasterSoundF8, LV_OBJ_FLAG_CHECKABLE );   /// Flags

lv_obj_t *cui_FuncPanelClose;
cui_FuncPanelClose = lv_imgbtn_create(cui_FuncPanel);
lv_imgbtn_set_src(cui_FuncPanelClose, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_close_png, NULL);
lv_obj_set_width( cui_FuncPanelClose, 40);
lv_obj_set_height( cui_FuncPanelClose, 40);
lv_obj_set_x( cui_FuncPanelClose, 59 );
lv_obj_set_y( cui_FuncPanelClose, 54 );
lv_obj_set_align( cui_FuncPanelClose, LV_ALIGN_CENTER );

lv_obj_t *cui_RoutePanel;
cui_RoutePanel = lv_obj_create(cui_ThrComp);
lv_obj_set_width( cui_RoutePanel, 170);
lv_obj_set_height( cui_RoutePanel, 210);
lv_obj_set_align( cui_RoutePanel, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_RoutePanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( cui_RoutePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_StartBlock;
cui_StartBlock = lv_dropdown_create(cui_RoutePanel);
lv_dropdown_set_options( cui_StartBlock, "\nBlk 0\nBlk 1\nBlk 2\nBlk 3\nBlk 4\nBlk 5\nBlk 6\nBlk 7\nBlk 8\nBk 9" );
lv_obj_set_width( cui_StartBlock, 80);
lv_obj_set_height( cui_StartBlock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_StartBlock, -8 );
lv_obj_set_y( cui_StartBlock, -70 );
lv_obj_set_align( cui_StartBlock, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_StartBlock, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_bg_color(cui_StartBlock, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_StartBlock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_StartBlock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_StartBlock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_StartBlock, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_StartBlock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_StartBlock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_StartBlock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_StartBlock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(cui_StartBlock), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(cui_StartBlock), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(cui_StartBlock), lv_color_hex(0xFFA0A0),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(cui_StartBlock), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(cui_StartBlock), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(cui_StartBlock), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(cui_StartBlock), lv_color_hex(0xFFA0A0),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(cui_StartBlock), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_t *cui_StartBlk;
cui_StartBlk = lv_label_create(cui_StartBlock);
lv_obj_set_width( cui_StartBlk, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_StartBlk, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_StartBlk, -1 );
lv_obj_set_y( cui_StartBlk, -23 );
lv_label_set_text(cui_StartBlk,"Start Blk");

lv_obj_t *cui_RouteSel;
cui_RouteSel = lv_dropdown_create(cui_RoutePanel);
lv_dropdown_set_options( cui_RouteSel, "" );
lv_obj_set_width( cui_RouteSel, 100);
lv_obj_set_height( cui_RouteSel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_RouteSel, 0 );
lv_obj_set_y( cui_RouteSel, -17 );
lv_obj_set_align( cui_RouteSel, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_RouteSel, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_bg_color(cui_RouteSel, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_RouteSel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_RouteSel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_RouteSel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_RouteSel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_RouteSel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_RouteSel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_RouteSel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_RouteSel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label2;
cui_Label2 = lv_label_create(cui_RouteSel);
lv_obj_set_width( cui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label2, 0 );
lv_obj_set_y( cui_Label2, -22 );
lv_label_set_text(cui_Label2,"Route");

lv_obj_t *cui_RouteStart;
cui_RouteStart = lv_btn_create(cui_RoutePanel);
lv_obj_set_width( cui_RouteStart, 100);
lv_obj_set_height( cui_RouteStart, 30);
lv_obj_set_x( cui_RouteStart, 0 );
lv_obj_set_y( cui_RouteStart, 27 );
lv_obj_set_align( cui_RouteStart, LV_ALIGN_CENTER );
lv_obj_add_state( cui_RouteStart, LV_STATE_USER_1 );     /// States
lv_obj_add_flag( cui_RouteStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_RouteStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_RouteStart, lv_color_hex(0xFF6060), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_RouteStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_RouteStart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_RouteStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_RouteStart, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_RouteStart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_RouteStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_RouteStart, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_RouteStart, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(cui_RouteStart, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(cui_RouteStart, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_RouteStart, lv_color_hex(0x60FF60), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(cui_RouteStart, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_color(cui_RouteStart, lv_color_hex(0xFF6060), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_opa(cui_RouteStart, 255, LV_PART_MAIN| LV_STATE_USER_2);

lv_obj_t *cui_ROuteBtnLabel;
cui_ROuteBtnLabel = lv_label_create(cui_RouteStart);
lv_obj_set_width( cui_ROuteBtnLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ROuteBtnLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_ROuteBtnLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_ROuteBtnLabel,"START");
lv_obj_set_style_text_color(cui_ROuteBtnLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ROuteBtnLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_RouteClose;
cui_RouteClose = lv_imgbtn_create(cui_RoutePanel);
lv_imgbtn_set_src(cui_RouteClose, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_close_png, NULL);
lv_obj_set_width( cui_RouteClose, 40);
lv_obj_set_height( cui_RouteClose, 40);
lv_obj_set_x( cui_RouteClose, 0 );
lv_obj_set_y( cui_RouteClose, 75 );
lv_obj_set_align( cui_RouteClose, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_THRCOMP_NUM);
children[UI_COMP_THRCOMP_THRCOMP] = cui_ThrComp;
children[UI_COMP_THRCOMP_LOCOTHR] = cui_LocoThr;
children[UI_COMP_THRCOMP_LOCOSPEED] = cui_LocoSpeed;
children[UI_COMP_THRCOMP_LOCONAME] = cui_LocoName;
children[UI_COMP_THRCOMP_LOCOREV] = cui_LocoRev;
children[UI_COMP_THRCOMP_HORN] = cui_horn;
children[UI_COMP_THRCOMP_ROUTEBTN] = cui_RouteBtn;
children[UI_COMP_THRCOMP_ROUTEBTN_ROUTELABEL] = cui_RouteLabel;
children[UI_COMP_THRCOMP_FUNCBUTTON] = cui_FuncButton;
children[UI_COMP_THRCOMP_FUNCBUTTON_FUNCLABEL] = cui_FuncLabel;
children[UI_COMP_THRCOMP_FUNCPANEL] = cui_FuncPanel;
children[UI_COMP_THRCOMP_FUNCPANEL_HEADLIGHTF0] = cui_HeadLightF0;
children[UI_COMP_THRCOMP_FUNCPANEL_HEADLIGHTF0_LABELF0] = cui_LabelF0;
children[UI_COMP_THRCOMP_FUNCPANEL_COUPLERF3] = cui_CouplerF3;
children[UI_COMP_THRCOMP_FUNCPANEL_COUPLERF3_LABELF3] = cui_LabelF3;
children[UI_COMP_THRCOMP_FUNCPANEL_FLANGEF7] = cui_FlangeF7;
children[UI_COMP_THRCOMP_FUNCPANEL_FLANGEF7_LABELF7] = cui_LabelF7;
children[UI_COMP_THRCOMP_FUNCPANEL_RADIATORF11] = cui_RadiatorF11;
children[UI_COMP_THRCOMP_FUNCPANEL_RADIATORF11_LABELF11] = cui_LabelF11;
children[UI_COMP_THRCOMP_FUNCPANEL_MASTERSOUNDF8] = cui_MasterSoundF8;
children[UI_COMP_THRCOMP_FUNCPANEL_FUNCPANELCLOSE] = cui_FuncPanelClose;
children[UI_COMP_THRCOMP_ROUTEPANEL] = cui_RoutePanel;
children[UI_COMP_THRCOMP_ROUTEPANEL_STARTBLOCK] = cui_StartBlock;
children[UI_COMP_THRCOMP_ROUTEPANEL_STARTBLOCK_STARTBLK] = cui_StartBlk;
children[UI_COMP_THRCOMP_ROUTEPANEL_ROUTESEL] = cui_RouteSel;
children[UI_COMP_THRCOMP_ROUTEPANEL_ROUTESEL_LABEL2] = cui_Label2;
children[UI_COMP_THRCOMP_ROUTEPANEL_ROUTESTART] = cui_RouteStart;
children[UI_COMP_THRCOMP_ROUTEPANEL_ROUTESTART_ROUTEBTNLABEL] = cui_ROuteBtnLabel;
children[UI_COMP_THRCOMP_ROUTEPANEL_ROUTECLOSE] = cui_RouteClose;
lv_obj_add_event_cb(cui_ThrComp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ThrComp, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_LocoThr, ui_event_comp_ThrComp_LocoThr, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_LocoName, ui_event_comp_ThrComp_LocoName, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_LocoRev, ui_event_comp_ThrComp_LocoRev, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_horn, ui_event_comp_ThrComp_horn, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_RouteBtn, ui_event_comp_ThrComp_RouteBtn, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_FuncButton, ui_event_comp_ThrComp_FuncButton, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_HeadLightF0, ui_event_comp_ThrComp_HeadLightF0, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_CouplerF3, ui_event_comp_ThrComp_CouplerF3, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_FlangeF7, ui_event_comp_ThrComp_FlangeF7, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_RadiatorF11, ui_event_comp_ThrComp_RadiatorF11, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_MasterSoundF8, ui_event_comp_ThrComp_MasterSoundF8, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_FuncPanelClose, ui_event_comp_ThrComp_FuncPanelClose, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_StartBlock, ui_event_comp_ThrComp_StartBlock, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_RouteStart, ui_event_comp_ThrComp_RouteStart, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_RouteClose, ui_event_comp_ThrComp_RouteClose, LV_EVENT_ALL, children);
ui_comp_ThrComp_create_hook(cui_ThrComp);
return cui_ThrComp; 
}

