// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#include "ui.h"

void ui_event_comp_ThrComp_LocoThr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( comp_ThrComp[UI_COMP_THRCOMP_LOCOSPEED], target, "", "");
}
}

void ui_event_comp_ThrComp_FuncButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_ThrComp = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_funcPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

// COMPONENT ThrComp

lv_obj_t *ui_ThrComp_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ThrComp;
cui_ThrComp = lv_obj_create(comp_parent);
lv_obj_set_width( cui_ThrComp, 150);
lv_obj_set_height( cui_ThrComp, 210);
lv_obj_set_x( cui_ThrComp, -20 );
lv_obj_set_y( cui_ThrComp, -20 );
lv_obj_set_align( cui_ThrComp, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ThrComp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_ThrComp, lv_color_hex(0xE0DEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ThrComp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoThr;
cui_LocoThr = lv_slider_create(cui_ThrComp);
lv_slider_set_range(cui_LocoThr, 0,128);
lv_slider_set_value( cui_LocoThr, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(cui_LocoThr)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( cui_LocoThr, 0, LV_ANIM_OFF);
lv_obj_set_width( cui_LocoThr, 15);
lv_obj_set_height( cui_LocoThr, 150);
lv_obj_set_x( cui_LocoThr, 60 );
lv_obj_set_y( cui_LocoThr, -10 );
lv_obj_set_style_bg_color(cui_LocoThr, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoThr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_LocoThr, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_LocoThr, lv_color_hex(0xC90000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoThr, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_LocoThr, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoThr, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_LocoThr, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_LocoThr, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_LocoThr, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoSpeed;
cui_LocoSpeed = lv_label_create(cui_ThrComp);
lv_obj_set_width( cui_LocoSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LocoSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LocoSpeed, 85 );
lv_obj_set_y( cui_LocoSpeed, 0 );
lv_label_set_text(cui_LocoSpeed,"0");
lv_obj_set_style_text_color(cui_LocoSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LocoSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_LocoSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LocoSpeed, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_LocoSpeed, lv_color_hex(0xF1F9D4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoName;
cui_LocoName = lv_dropdown_create(cui_ThrComp);
lv_dropdown_set_dir( cui_LocoName, LV_DIR_TOP);
lv_dropdown_set_options( cui_LocoName, "" );
lv_obj_set_width( cui_LocoName, 110);
lv_obj_set_height( cui_LocoName, 30);
lv_obj_set_x( cui_LocoName, 10 );
lv_obj_set_y( cui_LocoName, 155 );
lv_obj_add_flag( cui_LocoName, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_decor(cui_LocoName, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LocoName, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_LocoName, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_LocoName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_LocoName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_LocoName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_LocoName, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_LocoName, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(cui_LocoName, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LocoName, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(cui_LocoName, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(cui_LocoName, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_LocoName, LV_TEXT_ALIGN_AUTO, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LocoName, &lv_font_montserrat_18, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(lv_dropdown_get_list(cui_LocoName), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(cui_LocoName), &lv_font_montserrat_12,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(lv_dropdown_get_list(cui_LocoName), LV_TEXT_ALIGN_CENTER,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(cui_LocoName), &lv_font_montserrat_12,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(cui_LocoName), lv_color_hex(0x70F9EB),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(cui_LocoName), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_t *cui_LocoRev;
cui_LocoRev = lv_imgbtn_create(cui_ThrComp);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_loco_rev_png, NULL);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(cui_LocoRev, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_loco_rev_png, NULL);
lv_obj_set_width( cui_LocoRev, 40);
lv_obj_set_height( cui_LocoRev, 40);
lv_obj_set_x( cui_LocoRev, 0 );
lv_obj_set_y( cui_LocoRev, 60 );
lv_obj_add_flag( cui_LocoRev, LV_OBJ_FLAG_CHECKABLE );   /// Flags

lv_obj_t *cui_horn;
cui_horn = lv_imgbtn_create(cui_ThrComp);
lv_imgbtn_set_src(cui_horn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_horn_png, NULL);
lv_imgbtn_set_src(cui_horn, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sound_wave_png, NULL);
lv_obj_set_width( cui_horn, 32);
lv_obj_set_height( cui_horn, 32);
lv_obj_set_x( cui_horn, 0 );
lv_obj_set_y( cui_horn, 109 );

lv_obj_t *cui_FuncButton;
cui_FuncButton = lv_btn_create(cui_ThrComp);
lv_obj_set_width( cui_FuncButton, 40);
lv_obj_set_height( cui_FuncButton, 40);
lv_obj_add_flag( cui_FuncButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_FuncButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_FuncButton, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_FuncButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_FuncButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_FuncButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_FuncButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_FuncButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_FuncButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_FuncButton, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_FuncButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_FuncLabel;
cui_FuncLabel = lv_label_create(cui_FuncButton);
lv_obj_set_width( cui_FuncLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_FuncLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_FuncLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_FuncLabel,"Fn");
lv_obj_set_style_text_color(cui_FuncLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_FuncLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_THRCOMP_NUM);
children[UI_COMP_THRCOMP_THRCOMP] = cui_ThrComp;
children[UI_COMP_THRCOMP_LOCOTHR] = cui_LocoThr;
children[UI_COMP_THRCOMP_LOCOSPEED] = cui_LocoSpeed;
children[UI_COMP_THRCOMP_LOCONAME] = cui_LocoName;
children[UI_COMP_THRCOMP_LOCOREV] = cui_LocoRev;
children[UI_COMP_THRCOMP_HORN] = cui_horn;
children[UI_COMP_THRCOMP_FUNCBUTTON] = cui_FuncButton;
children[UI_COMP_THRCOMP_FUNCBUTTON_FUNCLABEL] = cui_FuncLabel;
lv_obj_add_event_cb(cui_ThrComp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ThrComp, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_LocoThr, ui_event_comp_ThrComp_LocoThr, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_FuncButton, ui_event_comp_ThrComp_FuncButton, LV_EVENT_ALL, children);
ui_comp_ThrComp_create_hook(cui_ThrComp);
return cui_ThrComp; 
}

