// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: esp32_tft_throttle

#include "ui.h"

void ui_comp_ThrComp_create_hook( lv_obj_t * comp)
{
}
