// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: esp32_tft_throttle

#include "ui.h"
#include <Arduino.h>
#include "my_turnout.h"

static char dbgStr[80];

//------------------------------------------------------------
// get dropdown menu widget for given throttle
//------------------------------------------------------------

lv_obj_t*	getLocoNameDropdown(int thr_idx)
{
	lv_obj_t*	  comp = NULL;
		
	switch (thr_idx) {
		case 0: comp = ui_ThrComp0; break;
		case 1: comp = ui_ThrComp1; break;
		case 2: comp = ui_ThrComp2; break;
		default: break;
	}
	if (!comp) return NULL;
	return ui_comp_get_child(comp, UI_COMP_THRCOMP_LOCONAME);
}


int getThrottleIdx(lv_obj_t *target)
{
  lv_obj_t* comp = lv_obj_get_parent(target);

	int thr_idx = -1;
	if 			(comp == ui_ThrComp0) { thr_idx = 0; }
	else if (comp == ui_ThrComp1) { thr_idx = 1; }
	else if (comp == ui_ThrComp2) { thr_idx = 2; }
	return thr_idx;
}

//------------------------------------------------------------
// Sets loco names dropdown menus with loco address and names
// This is done when a new roster is received from DCC-EX 
// at startup time.
//-------------------------------------------------------------
void clearLocoList(int thr_idx) 
{
	lv_obj_t* dropdown = getLocoNameDropdown(thr_idx);
	if (!dropdown) return;
	lv_dropdown_clear_options(dropdown);
}


void setLocoList(int thr_idx, int loco_idx, const char* name, uint32_t addr) 
{
	lv_obj_t* dropdown = getLocoNameDropdown(thr_idx);
	if (!dropdown) return;

	snprintf(dbgStr, sizeof(dbgStr), "%d: %s", addr, name);
	c_serial_print(dbgStr);
	lv_dropdown_add_option(dropdown, dbgStr, loco_idx);
}

//------------------------------------------------------------
// assign a throttle to a loco index in dropdown menu
// This is called to assign a loco to a throttle at startup.
//------------------------------------------------------------

void selectLoco(int thr_idx, int loco_idx)
{
	lv_obj_t* dropdown = getLocoNameDropdown(thr_idx);
	if (!dropdown) return;

	snprintf(dbgStr, sizeof(dbgStr), "Select Loco: throttle=%d, locoIdx=%d\n", thr_idx, loco_idx);
	c_serial_print(dbgStr);
	lv_dropdown_set_selected(dropdown, loco_idx);
}


//------------------------------------------------------
// A new loco is selected from dropdown menu. 
// Associate the loco with throttle slider
//------------------------------------------------------
void setThrottleLoco(lv_event_t * e)
{
	char		locoStr[40];

	lv_obj_t* dropdown = lv_event_get_current_target(e);
	int thr_idx = getThrottleIdx(dropdown);
	if (thr_idx < 0) return;

	int loco_idx = lv_dropdown_get_selected(dropdown);
	lv_dropdown_get_selected_str(dropdown, locoStr, sizeof(locoStr));
	snprintf(dbgStr, sizeof(dbgStr), "setThrottleLoco: loco_idx=%d, str=%s\n", loco_idx, locoStr);
	c_serial_print(dbgStr);
	assignLocoToThrottle(thr_idx, loco_idx);
}

//------------------------------------------------------------
// set locomotive speed from the slider widget
//------------------------------------------------------------

void setLocoSpeed(lv_event_t * e)
{
	lv_obj_t* slider = lv_event_get_current_target(e);
	lv_obj_t* comp = lv_obj_get_parent(slider);

	lv_obj_t* dirBtn = ui_comp_get_child(comp, UI_COMP_THRCOMP_LOCOREV);;
	int32_t speedVal = lv_slider_get_value(slider);
	
	int thr_idx = getThrottleIdx(slider);
	if (thr_idx < 0) return;

	int32_t dir = (lv_obj_has_state(dirBtn, LV_STATE_CHECKED) ? 1 : 0);
	setDccLocoSpeed(thr_idx, speedVal, dir);
}

//------------------------------------------------------------
// set locomotive direction
//------------------------------------------------------------

void setLocoReverse(lv_event_t * e)
{
	lv_obj_t* dirBtn = lv_event_get_current_target(e);
	lv_obj_t* comp = lv_obj_get_parent(dirBtn);
	lv_obj_t* slider = ui_comp_get_child(comp, UI_COMP_THRCOMP_LOCOTHR);;

	int thr_idx = getThrottleIdx(dirBtn);
	if (thr_idx < 0) return;

	int32_t speedVal = lv_slider_get_value(slider);
	int32_t dir = (lv_obj_has_state(dirBtn, LV_STATE_CHECKED) ? 1 : 0);
	setDccLocoSpeed(thr_idx, speedVal, dir);
}


void setLocoHorn(lv_event_t * e)
{
	lv_obj_t* hornBtn = lv_event_get_current_target(e);

	int thr_idx = getThrottleIdx(hornBtn);
	if (thr_idx < 0) return;

	lv_state_t btnState = lv_obj_get_state(hornBtn);
	bool btnChecked = (btnState == LV_STATE_CHECKED) || (btnState == LV_STATE_PRESSED);


	snprintf(dbgStr, sizeof(dbgStr), "setLocoHorn: pressed=%d\n", btnChecked);
	c_serial_print(dbgStr);

	int32_t val = (btnChecked) ? 1 : 0;
	setDccHorn(thr_idx, val);
}

//-----------------------------------------------------
// Loco Function setting
//-----------------------------------------------------

static int curFuncBtnIdx = -1;

// Opened the function panel. Save the index of throttle for which the function panel as opened.
void openLocoFunc(lv_event_t * e)
{

	lv_obj_t*	funcOpenBtn = lv_event_get_current_target(e);
	// set curFuncBtnIdx which will be later used by 'setLocoFunc'
	curFuncBtnIdx = getThrottleIdx(funcOpenBtn);
	snprintf(dbgStr, sizeof(dbgStr), "OpenFuncPanel: thrIdx=%d\n", curFuncBtnIdx);
	c_serial_print(dbgStr);
}

void setLocoFunc(lv_event_t * e)
{
	lv_obj_t* funcBtn = lv_event_get_current_target(e);

	int func_num = -1;
	if 			(funcBtn == ui_HeadLightF0)	{ func_num = 0; }
	else if (funcBtn == ui_CouplerF3)	{ func_num = 3; }
	else if (funcBtn == ui_FlangeF7)	{ func_num = 7; }
	else if (funcBtn == ui_MasterSoundF8)	{ func_num = 8; }
	else if (funcBtn == ui_RadiatorF11)	{ func_num = 11; }

	snprintf(dbgStr, sizeof(dbgStr), "selectFunc: thrIdx=%d, func=%d\n", curFuncBtnIdx, func_num);
	c_serial_print(dbgStr);

	if (curFuncBtnIdx < 0 || func_num < 0)
		return;

	bool btnChecked = lv_obj_has_state(funcBtn, LV_STATE_CHECKED);
	int32_t val = (btnChecked) ? 1 : 0;

	setDccFunc(curFuncBtnIdx, func_num, val);
}

void showLocoRoster(lv_event_t * e)
{
	// Your code here
}

void showTrainRoutes(lv_event_t * e)
{
	// Your code here
}

void showRoutes(lv_event_t * e)
{
	// Your code here
}

void setTurnOut(lv_event_t * e)
{
	lv_obj_t* turnoutBtn = lv_event_get_current_target(e);

	int	tidx = -1;
	if 			(turnoutBtn == ui_TurnTL0Set)	{ tidx = TURNOUT_TL0; }
	else if (turnoutBtn == ui_TurnTL2Set)	{ tidx = TURNOUT_TL2; }
	else if (turnoutBtn == ui_TurnTR0Set)	{ tidx = TURNOUT_TR0; }
	else if (turnoutBtn == ui_TurnTR2Set)	{ tidx = TURNOUT_TR2; }
	else if (turnoutBtn == ui_TurnXCSet)	{ tidx = TURNOUT_XC; }
	if (tidx < 0) return;
		
	int32_t val = (lv_obj_has_state(turnoutBtn, LV_STATE_CHECKED) ? 1 : 0);
	setDccTurnout(tidx, val);
}


void powerOff(lv_event_t * e)
{
	gotoSleep();
}

void resetEsp(lv_event_t * e)
{
	reset();
}
