// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: esp32_tft_throttle

#include "ui.h"
#include <Arduino.h>
#include "dcc_funcs.h"
#include "autorun.h"

static char dbgStr[80];

//------------------------------------------------------------
// get dropdown menu widget for given throttle
//------------------------------------------------------------

lv_obj_t*	getLocoNameDropdown(int thr_idx)
{
	lv_obj_t*	  comp = NULL;
		
	switch (thr_idx) {
		case 0: comp = ui_ThrComp0; break;
		case 1: comp = ui_ThrComp1; break;
		case 2: comp = ui_ThrComp2; break;
		default: break;
	}
	if (!comp) return NULL;
	return ui_comp_get_child(comp, UI_COMP_THRCOMP_LOCONAME);
}


int getThrottleIdx(lv_obj_t *target)
{
  lv_obj_t* comp = lv_obj_get_parent(target);

	int thr_idx = -1;
	if 			(comp == ui_ThrComp0) { thr_idx = 0; }
	else if (comp == ui_ThrComp1) { thr_idx = 1; }
	else if (comp == ui_ThrComp2) { thr_idx = 2; }
	return thr_idx;
}

//------------------------------------------------------------
// Sets loco names dropdown menus with loco address and names
// This is done when a new roster is received from DCC-EX 
// at startup time.
//-------------------------------------------------------------
void clearLocoList(int thr_idx) 
{
	lv_obj_t* dropdown = getLocoNameDropdown(thr_idx);
	if (!dropdown) return;
	lv_dropdown_clear_options(dropdown);
}


void setLocoList(int thr_idx, int loco_idx, const char* name, uint32_t addr) 
{
	lv_obj_t* dropdown = getLocoNameDropdown(thr_idx);
	if (!dropdown) return;

	snprintf(dbgStr, sizeof(dbgStr), "%d: %s", addr, name);
	c_serial_print(dbgStr);
	lv_dropdown_add_option(dropdown, dbgStr, loco_idx);
}

//------------------------------------------------------------
// assign a throttle to a loco index in dropdown menu
// This is called to assign a loco to a throttle at startup.
//------------------------------------------------------------

void selectLoco(int thr_idx, int loco_idx)
{
	lv_obj_t* dropdown = getLocoNameDropdown(thr_idx);
	if (!dropdown) return;

	snprintf(dbgStr, sizeof(dbgStr), "Select Loco: throttle=%d, locoIdx=%d\n", thr_idx, loco_idx);
	c_serial_print(dbgStr);
	lv_dropdown_set_selected(dropdown, loco_idx);
}


//------------------------------------------------------
// A new loco is selected from dropdown menu. 
// Associate the loco with throttle slider
//------------------------------------------------------
void setThrottleLoco(lv_event_t * e)
{
	char		locoStr[40];

	lv_obj_t* dropdown = lv_event_get_current_target(e);
	int thr_idx = getThrottleIdx(dropdown);
	if (thr_idx < 0) return;

	int loco_idx = lv_dropdown_get_selected(dropdown);
	lv_dropdown_get_selected_str(dropdown, locoStr, sizeof(locoStr));
	snprintf(dbgStr, sizeof(dbgStr), "setThrottleLoco: loco_idx=%d, str=%s\n", loco_idx, locoStr);
	c_serial_print(dbgStr);
	assignLocoToThrottle(thr_idx, loco_idx);
}

//------------------------------------------------------------
// set locomotive speed from the slider widget
//------------------------------------------------------------

void setLocoSpeed(lv_event_t * e)
{
	lv_obj_t* slider = lv_event_get_current_target(e);
	lv_obj_t* comp = lv_obj_get_parent(slider);

	lv_obj_t* dirBtn = ui_comp_get_child(comp, UI_COMP_THRCOMP_LOCOREV);;
	int32_t speedVal = lv_slider_get_value(slider);
	
	int thr_idx = getThrottleIdx(slider);
	if (thr_idx < 0) return;

	int32_t dir = (lv_obj_has_state(dirBtn, LV_STATE_CHECKED) ? 1 : 0);
	setDccLocoSpeed(thr_idx, speedVal, dir);
}

//------------------------------------------------------------
// set locomotive direction
//------------------------------------------------------------

void setLocoReverse(lv_event_t * e)
{
	lv_obj_t* dirBtn = lv_event_get_current_target(e);
	lv_obj_t* comp = lv_obj_get_parent(dirBtn);
	lv_obj_t* slider = ui_comp_get_child(comp, UI_COMP_THRCOMP_LOCOTHR);;

	int thr_idx = getThrottleIdx(dirBtn);
	if (thr_idx < 0) return;

	int32_t speedVal = lv_slider_get_value(slider);
	int32_t dir = (lv_obj_has_state(dirBtn, LV_STATE_CHECKED) ? 1 : 0);
	setDccLocoSpeed(thr_idx, speedVal, dir);
}


void setLocoHorn(lv_event_t * e)
{
	lv_obj_t* hornBtn = lv_event_get_current_target(e);

	int thr_idx = getThrottleIdx(hornBtn);
	if (thr_idx < 0) return;

	lv_state_t btnState = lv_obj_get_state(hornBtn);
	int8_t val = lv_obj_has_state(hornBtn, LV_STATE_PRESSED) ? 1 : 0;

	snprintf(dbgStr, sizeof(dbgStr), "setLocoHorn: state=%d, pressed=%d\n", btnState, val);
	c_serial_print(dbgStr);

	setDccHorn(thr_idx, val);
}

//-----------------------------------------------------
// Loco Function setting
//-----------------------------------------------------

// Opened the function panel. Save the index of throttle for which the function panel as opened.
void openLocoFunc(lv_event_t * e)
{
	lv_obj_t*	funcOpenBtn = lv_event_get_target(e);
	lv_obj_t* thrPanel = lv_obj_get_parent(funcOpenBtn);
	lv_obj_t* funcPanel = ui_comp_get_child(thrPanel, UI_COMP_THRCOMP_FUNCPANEL);

	// set curFuncBtnIdx which will be later used by 'setLocoFunc'
	int thrIdx = getThrottleIdx(funcOpenBtn);
	snprintf(dbgStr, sizeof(dbgStr), "OpenFuncPanel: thrIdx=%d\n", thrIdx);
	c_serial_print(dbgStr);

	// change the background of func panel based on throttle index
	lv_color_t bg_color = lv_obj_get_style_bg_color(funcOpenBtn, LV_PART_MAIN);
	lv_obj_set_style_bg_color(funcPanel, bg_color, LV_PART_MAIN | LV_STATE_DEFAULT );
}


void setLocoFunc(lv_event_t *e, uint8_t func_idx, lv_state_t state_to_check)
{
	lv_obj_t* funcBtn = lv_event_get_target(e);
	lv_obj_t* funcPanel = lv_obj_get_parent(funcBtn);

	int thrIdx = getThrottleIdx(funcPanel);
	int val = (lv_obj_has_state(funcBtn, state_to_check)) ? 1 : 0;
	setDccFunc(thrIdx, func_idx, val);
}

void setLocoFunc0(lv_event_t * e)
{
	setLocoFunc(e, 0, LV_STATE_CHECKED);
}

void setLocoFunc3(lv_event_t * e)
{
	setLocoFunc(e, 3, LV_STATE_PRESSED);
}

void setLocoFunc7(lv_event_t * e)
{
	setLocoFunc(e, 7, LV_STATE_PRESSED);
}

void setLocoFunc11(lv_event_t * e)
{
	setLocoFunc(e, 11, LV_STATE_PRESSED);
}

void setLocoFunc8(lv_event_t * e)
{
	setLocoFunc(e, 8, LV_STATE_CHECKED);
}

//---------------------------------------------------------
// Assign starting block to each locomotive in roster
//---------------------------------------------------------

void setLocoBlk(lv_event_t * e)
{
	uint	loco_blk_idx;

  // Get the starting block index for each loco index
	for (uint lidx = 0; lidx < NUM_THROTTLES; ++lidx) {
		switch (lidx) {
			case 0: loco_blk_idx = lv_dropdown_get_selected(ui_Loco0BlkSel);	break;
			case 1: loco_blk_idx = lv_dropdown_get_selected(ui_Loco1BlkSel);	break;
  		case 2: loco_blk_idx = lv_dropdown_get_selected(ui_Loco2BlkSel);	break;
			default:
				snprintf(dbgStr, sizeof(dbgStr), "setLocoBlk: invalid loco index > %d\n", lidx);
				c_serial_print(dbgStr);
				return;
		}
		setLocoStartBlock(lidx, loco_blk_idx);
	}
}

//---------------------------------------------------------
//---------------------------------------------------------

void showRoutes(lv_event_t * e)
{
	// Your code here
}

//---------------------------------------------------------
//---------------------------------------------------------

void setTurnOut(lv_event_t * e)
{
	lv_obj_t* turnoutBtn = lv_event_get_current_target(e);

	int	tidx = -1;
	if 			(turnoutBtn == ui_TurnTL0Set)	{ tidx = TURNOUT_TL0; }
	else if (turnoutBtn == ui_TurnTL2Set)	{ tidx = TURNOUT_TL2; }
	else if (turnoutBtn == ui_TurnTR0Set)	{ tidx = TURNOUT_TR0; }
	else if (turnoutBtn == ui_TurnTR2Set)	{ tidx = TURNOUT_TR2; }
	else if (turnoutBtn == ui_TurnXCSet)	{ tidx = TURNOUT_XC; }
	if (tidx < 0) return;
		
	int32_t val = (lv_obj_has_state(turnoutBtn, LV_STATE_CHECKED) ? 1 : 0);
	setDccTurnout(tidx, val);
}

//-------------------------------------------------------------
// This function is called by the logic that calculates the signal
// aspect. 
//-------------------------------------------------------------

void setSignalAspect(enum SignalIds_e signal_id, uint32_t aspect_col)
{
	lv_obj_t* signalObj = NULL;

	switch (signal_id) {
		case SIGNAL_SHL0C:	signalObj = ui_SHL0C;		break;
		case SIGNAL_SHL1TC:	signalObj = ui_SHL1TC;		break;
		case SIGNAL_SHL1TD:	signalObj = ui_SHL1TD;		break;
		case SIGNAL_SHL2C:	signalObj = ui_SHL2C;		break;
		case SIGNAL_SHL2D:	signalObj = ui_SHL2D;		break;
		case SIGNAL_SHR0TC:	signalObj = ui_SHR0TC;		break;
		case SIGNAL_SHR0TD:	signalObj = ui_SHR0TD;		break;
		case SIGNAL_SHR1C:	signalObj = ui_SHR1C;		break;
		case SIGNAL_SHR2TC:	signalObj = ui_SHR2TC;		break;
		case SIGNAL_SHR2TD:	signalObj = ui_SHR2TD;		break;
		default:		break;
	}
	if (!signalObj) return;

  lv_color_t objColor = lv_color_hex(aspect_col);
  lv_obj_set_style_bg_color(signalObj, objColor, LV_PART_MAIN);
}

//---------------------------------------------------------
// Use block detection sensor to highlight a block of
// track on the layout panel
// Note: The tracks on the layout panels are made of 
// panel widgets. Some of the block tracks are made up 
// of multiple panels. This code needs to know which 
// block has multiple panels.
//---------------------------------------------------------

#define OBJ_ADD_STATE_CONTAINER(b)	\
		lv_obj_clear_state(ui_Blk ## b ## P0, old_state); \
		lv_obj_clear_state(ui_Blk ## b ## P1, old_state); \
		lv_obj_clear_state(ui_Blk ## b ## P2, old_state); \
		lv_obj_add_state(ui_Blk ## b ## P0, blk_state);	\
		lv_obj_add_state(ui_Blk ## b ## P1, blk_state);	\
		lv_obj_add_state(ui_Blk ## b ## P2, blk_state);
	
static lv_state_t objCurState[NUM_BLOCK_SENSORS] = {
	LV_STATE_DEFAULT,		// 0
	LV_STATE_DEFAULT,
	LV_STATE_DEFAULT,
	LV_STATE_DEFAULT,
	LV_STATE_DEFAULT,
	LV_STATE_DEFAULT,		// 5
	LV_STATE_DEFAULT,
	LV_STATE_DEFAULT,
	LV_STATE_DEFAULT,
	LV_STATE_DEFAULT
};

static lv_state_t locoStateIdx[NUM_THROTTLES] = {
	LV_STATE_USER_1, 
	LV_STATE_USER_2, 
	LV_STATE_USER_3
};


void setLayoutBlockHighlight(uint16_t sensor_idx, bool active)
{
	// set object state based on active. The object state will determine its style
	lv_state_t old_state = objCurState[sensor_idx];
	int locoIdx = locoInBlock[sensor_idx];
	lv_state_t	blk_state = (active) ? locoStateIdx[locoIdx] : LV_STATE_DEFAULT;
	snprintf(dbgStr, sizeof(dbgStr), "setLayoutBlockHighlight: sensor=%d, state=%d\n", sensor_idx, blk_state);
	c_serial_print(dbgStr);

	switch(sensor_idx) {
		case 0:		
			lv_obj_clear_state(ui_Block0, old_state);
			lv_obj_add_state(ui_Block0, blk_state);		
			break;
		
		case 1: 	// it is a container with 3 panels
			OBJ_ADD_STATE_CONTAINER(1)
			break;

		case 2:
			OBJ_ADD_STATE_CONTAINER(2)
			break;

		case 3:
			lv_obj_clear_state(ui_Block3, old_state);
			lv_obj_add_state(ui_Block3, blk_state);		
			break;

		case 4:
			OBJ_ADD_STATE_CONTAINER(4)
			break;

		case 5:
			OBJ_ADD_STATE_CONTAINER(5)
			break;

		case 6:
			lv_obj_clear_state(ui_Block6, old_state);
			lv_obj_add_state(ui_Block6, blk_state);		
			break;

		case 7:
			OBJ_ADD_STATE_CONTAINER(7)
			break;

		case 8:
			OBJ_ADD_STATE_CONTAINER(8)
			break;

		case 9:
			lv_obj_clear_state(ui_Block9, old_state);
			lv_obj_add_state(ui_Block9, blk_state);		
			break;

		default: return;
	}

	objCurState[sensor_idx] = blk_state;
}

//---------------------------------------------------------
// The keyboard input is used for sending raw commands to
// DCC-EX command station
//---------------------------------------------------------
void getKeyboardText(lv_event_t * e)
{
	lv_obj_t * kb = lv_event_get_target(e); 
	lv_obj_t * ta = lv_keyboard_get_textarea(kb); 
	
	if(ta != NULL) {
		const char * text_input = lv_textarea_get_text(ta); 
		sendDccExCmd(text_input);
	}
}



void powerOff(lv_event_t * e)
{
	gotoSleep();
}


void resetHal(lv_event_t * e)
{
		sendDccExCmd("D HAL RESET");
}
