// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void powerOff(lv_event_t * e);
void setTurnOut(lv_event_t * e);
void setLocoSpeed(lv_event_t * e);
void setThrottleLoco(lv_event_t * e);
void setLocoReverse(lv_event_t * e);
void setLocoHorn(lv_event_t * e);
void openLocoFunc(lv_event_t * e);
void setLocoFunc0(lv_event_t * e);
void setLocoFunc3(lv_event_t * e);
void setLocoFunc7(lv_event_t * e);
void setLocoFunc11(lv_event_t * e);
void setLocoFunc8(lv_event_t * e);
void setLocoBlk(lv_event_t * e);
void setRouteState(lv_event_t * e);
void getKeyboardText(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
