// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#include "ui.h"

lv_obj_t *ui_Home = NULL;lv_obj_t *ui_Logo = NULL;lv_obj_t *ui_MainTitle = NULL;lv_obj_t *ui_WifiLevel = NULL;lv_obj_t *ui_WifiLabel = NULL;lv_obj_t *ui_layoutPanel = NULL;lv_obj_t *ui_OutLoop0 = NULL;lv_obj_t *ui_OutLoopLabelB = NULL;lv_obj_t *ui_OutLoop1 = NULL;lv_obj_t *ui_OutLoopLabelA = NULL;lv_obj_t *ui_TownLoop = NULL;lv_obj_t *ui_TownLoopLabel = NULL;lv_obj_t *ui_Siding = NULL;lv_obj_t *ui_TurnXCSet = NULL;lv_obj_t *ui_TurnTL0Set = NULL;lv_obj_t *ui_TurnTR0Set = NULL;lv_obj_t *ui_TurnTL2Set = NULL;lv_obj_t *ui_TurnTR2Set = NULL;lv_obj_t *ui_SHL0C = NULL;lv_obj_t *ui_SHL1TD = NULL;lv_obj_t *ui_SHL1TC = NULL;lv_obj_t *ui_SHL2C = NULL;lv_obj_t *ui_SHL2D = NULL;lv_obj_t *ui_SHR0TC = NULL;lv_obj_t *ui_SHR0TD = NULL;lv_obj_t *ui_SHR1C = NULL;lv_obj_t *ui_SHR2TC = NULL;lv_obj_t *ui_SHR2TD = NULL;lv_obj_t *ui_SidingLabel = NULL;lv_obj_t *ui_ThrPanel = NULL;lv_obj_t *ui_ThrComp0 = NULL;lv_obj_t *ui_ThrComp1 = NULL;lv_obj_t *ui_ThrComp2 = NULL;lv_obj_t *ui_HomePowerOff = NULL;lv_obj_t *ui_RouteBtn = NULL;lv_obj_t *ui_RouteBtnLabel = NULL;lv_obj_t *ui_DccExBtn = NULL;lv_obj_t *ui_dccexKeyboard = NULL;lv_obj_t *ui_dccexCmdText = NULL;lv_obj_t *ui_keyboardClose = NULL;lv_obj_t *ui_CloseLabel = NULL;
// event funtions
void ui_event_TurnXCSet( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTL0Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTR0Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTL2Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTR2Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_ThrComp2_LocoThr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoSpeed( e );
}
}

void ui_event_HomePowerOff( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      powerOff( e );
}
}

void ui_event_RouteBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      showRoutes( e );
}
}

void ui_event_DccExBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_dccexCmdText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_dccexKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_keyboardClose, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_dccexKeyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      getKeyboardText( e );
}
}

void ui_event_keyboardClose( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_dccexCmdText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_dccexKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_keyboardClose, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Logo = lv_img_create(ui_Home);
lv_img_set_src(ui_Logo, &ui_img_vthrottle_logo_png);
lv_obj_set_width( ui_Logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Logo, -306 );
lv_obj_set_y( ui_Logo, 170 );
lv_obj_set_align( ui_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Logo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Logo,300);

ui_MainTitle = lv_label_create(ui_Home);
lv_obj_set_width( ui_MainTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainTitle, 0 );
lv_obj_set_y( ui_MainTitle, -225 );
lv_obj_set_align( ui_MainTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainTitle,"vThrottle");
lv_obj_set_style_text_color(ui_MainTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_MainTitle, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainTitle, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiLevel = lv_bar_create(ui_Home);
lv_bar_set_value(ui_WifiLevel,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_WifiLevel, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_WifiLevel, 80);
lv_obj_set_height( ui_WifiLevel, 10);
lv_obj_set_x( ui_WifiLevel, 70 );
lv_obj_set_y( ui_WifiLevel, 13 );
lv_obj_set_style_bg_color(ui_WifiLevel, lv_color_hex(0x97CFCD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiLevel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_WifiLevel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_WifiLevel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_WifiLevel, lv_color_hex(0x3334FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiLevel, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_WifiLabel = lv_label_create(ui_Home);
lv_obj_set_width( ui_WifiLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiLabel, 30 );
lv_obj_set_y( ui_WifiLabel, 10 );
lv_label_set_text(ui_WifiLabel,"Wifi:");
lv_obj_set_style_text_color(ui_WifiLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WifiLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_layoutPanel = lv_obj_create(ui_Home);
lv_obj_set_width( ui_layoutPanel, 740);
lv_obj_set_height( ui_layoutPanel, 230);
lv_obj_set_x( ui_layoutPanel, 30 );
lv_obj_set_y( ui_layoutPanel, 30 );
lv_obj_clear_flag( ui_layoutPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_layoutPanel, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_layoutPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_layoutPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_layoutPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_layoutPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_layoutPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_layoutPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_layoutPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_layoutPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_layoutPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_layoutPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoop0 = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_OutLoop0);
lv_obj_set_width( ui_OutLoop0, 700);
lv_obj_set_height( ui_OutLoop0, 180);
lv_obj_set_x( ui_OutLoop0, 1 );
lv_obj_set_y( ui_OutLoop0, -6 );
lv_obj_clear_flag( ui_OutLoop0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_OutLoop0, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OutLoop0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OutLoop0, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoopLabelB = lv_label_create(ui_OutLoop0);
lv_obj_set_width( ui_OutLoopLabelB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OutLoopLabelB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutLoopLabelB, 78 );
lv_obj_set_y( ui_OutLoopLabelB, 81 );
lv_obj_set_align( ui_OutLoopLabelB, LV_ALIGN_CENTER );
lv_label_set_text(ui_OutLoopLabelB,"Out Loop B");
lv_obj_set_style_text_color(ui_OutLoopLabelB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OutLoopLabelB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OutLoopLabelB, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutLoopLabelB, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutLoopLabelB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoop1 = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_OutLoop1);
lv_obj_set_width( ui_OutLoop1, 650);
lv_obj_set_height( ui_OutLoop1, 150);
lv_obj_set_x( ui_OutLoop1, 25 );
lv_obj_set_y( ui_OutLoop1, 9 );
lv_obj_clear_flag( ui_OutLoop1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_OutLoop1, lv_color_hex(0xFFB464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OutLoop1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OutLoop1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoopLabelA = lv_label_create(ui_OutLoop1);
lv_obj_set_width( ui_OutLoopLabelA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OutLoopLabelA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutLoopLabelA, 13 );
lv_obj_set_y( ui_OutLoopLabelA, 65 );
lv_obj_set_align( ui_OutLoopLabelA, LV_ALIGN_CENTER );
lv_label_set_text(ui_OutLoopLabelA,"Out Loop A");
lv_obj_set_style_text_color(ui_OutLoopLabelA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OutLoopLabelA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OutLoopLabelA, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutLoopLabelA, lv_color_hex(0xFFB4C4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutLoopLabelA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TownLoop = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_TownLoop);
lv_obj_set_width( ui_TownLoop, 600);
lv_obj_set_height( ui_TownLoop, 80);
lv_obj_set_x( ui_TownLoop, 50 );
lv_obj_set_y( ui_TownLoop, 64 );
lv_obj_add_state( ui_TownLoop, LV_STATE_CHECKED | LV_STATE_PRESSED );     /// States
lv_obj_clear_flag( ui_TownLoop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_TownLoop, lv_color_hex(0xC10000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TownLoop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TownLoop, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TownLoopLabel = lv_label_create(ui_TownLoop);
lv_obj_set_width( ui_TownLoopLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TownLoopLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TownLoopLabel, -54 );
lv_obj_set_y( ui_TownLoopLabel, 29 );
lv_obj_set_align( ui_TownLoopLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TownLoopLabel,"Town  Loop");
lv_obj_set_style_text_color(ui_TownLoopLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TownLoopLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TownLoopLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TownLoopLabel, lv_color_hex(0xC10000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TownLoopLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Siding = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_Siding);
lv_obj_set_width( ui_Siding, 520);
lv_obj_set_height( ui_Siding, 5);
lv_obj_set_x( ui_Siding, 90 );
lv_obj_set_y( ui_Siding, 184 );
lv_obj_clear_flag( ui_Siding, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Siding, lv_color_hex(0x4F7C85), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Siding, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Siding, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnXCSet = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_xc_png, NULL);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_tunrout_xc1_png, NULL);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_xc_png, NULL);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tunrout_xc1_png, NULL);
lv_obj_set_width( ui_TurnXCSet, 30);
lv_obj_set_height( ui_TurnXCSet, 30);
lv_obj_set_x( ui_TurnXCSet, 335 );
lv_obj_set_y( ui_TurnXCSet, -11 );
lv_obj_add_flag( ui_TurnXCSet, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_TurnTL0Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tl0_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tl0_1_png, NULL);
lv_obj_set_width( ui_TurnTL0Set, 30);
lv_obj_set_height( ui_TurnTL0Set, 30);
lv_obj_set_x( ui_TurnTL0Set, 100 );
lv_obj_set_y( ui_TurnTL0Set, 135 );
lv_obj_add_flag( ui_TurnTL0Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTL0Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTL0Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTL0Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnTR0Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tr0_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tr0_1_png, NULL);
lv_obj_set_width( ui_TurnTR0Set, 30);
lv_obj_set_height( ui_TurnTR0Set, 30);
lv_obj_set_x( ui_TurnTR0Set, 570 );
lv_obj_set_y( ui_TurnTR0Set, 135 );
lv_obj_add_flag( ui_TurnTR0Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTR0Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTR0Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTR0Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnTL2Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tl2_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tl2_1_png, NULL);
lv_obj_set_width( ui_TurnTL2Set, 30);
lv_obj_set_height( ui_TurnTL2Set, 30);
lv_obj_set_x( ui_TurnTL2Set, 60 );
lv_obj_set_y( ui_TurnTL2Set, 164 );
lv_obj_add_flag( ui_TurnTL2Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTL2Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTL2Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTL2Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnTR2Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tr2_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tr2_1_png, NULL);
lv_obj_set_width( ui_TurnTR2Set, 30);
lv_obj_set_height( ui_TurnTR2Set, 30);
lv_obj_set_x( ui_TurnTR2Set, 610 );
lv_obj_set_y( ui_TurnTR2Set, 164 );
lv_obj_add_flag( ui_TurnTR2Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTR2Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTR2Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTR2Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SHL0C = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHL0C, 10);
lv_obj_set_height( ui_SHL0C, 10);
lv_obj_set_x( ui_SHL0C, 87 );
lv_obj_set_y( ui_SHL0C, 129 );
lv_obj_add_flag( ui_SHL0C, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHL0C, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHL0C, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHL0C, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHL0C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHL0C, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHL0C, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHL0C, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHL0C, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHL0C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHL0C, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHL0C, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHL0C, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHL0C, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHL0C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHL0C, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHL0C, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHL1TD = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHL1TD, 10);
lv_obj_set_height( ui_SHL1TD, 10);
lv_obj_set_x( ui_SHL1TD, 131 );
lv_obj_set_y( ui_SHL1TD, 145 );
lv_obj_add_flag( ui_SHL1TD, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHL1TD, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHL1TD, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHL1TD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHL1TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHL1TD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHL1TD, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHL1TD, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHL1TD, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHL1TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHL1TD, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHL1TD, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHL1TD, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHL1TD, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHL1TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHL1TD, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHL1TD, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHL1TC = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHL1TC, 10);
lv_obj_set_height( ui_SHL1TC, 10);
lv_obj_set_x( ui_SHL1TC, 87 );
lv_obj_set_y( ui_SHL1TC, 145 );
lv_obj_add_flag( ui_SHL1TC, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHL1TC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHL1TC, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHL1TC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHL1TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHL1TC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHL1TC, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHL1TC, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHL1TC, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHL1TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHL1TC, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHL1TC, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHL1TC, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHL1TC, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHL1TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHL1TC, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHL1TC, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHL2C = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHL2C, 10);
lv_obj_set_height( ui_SHL2C, 10);
lv_obj_set_x( ui_SHL2C, 48 );
lv_obj_set_y( ui_SHL2C, 159 );
lv_obj_add_flag( ui_SHL2C, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHL2C, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHL2C, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHL2C, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHL2C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHL2C, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHL2C, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHL2C, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHL2C, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHL2C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHL2C, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHL2C, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHL2C, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHL2C, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHL2C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHL2C, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHL2C, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHL2D = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHL2D, 10);
lv_obj_set_height( ui_SHL2D, 10);
lv_obj_set_x( ui_SHL2D, 96 );
lv_obj_set_y( ui_SHL2D, 174 );
lv_obj_add_flag( ui_SHL2D, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHL2D, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHL2D, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHL2D, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHL2D, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHL2D, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHL2D, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHL2D, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHL2D, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHL2D, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHL2D, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHL2D, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHL2D, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHL2D, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHL2D, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHL2D, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHL2D, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHR0TC = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHR0TC, 10);
lv_obj_set_height( ui_SHR0TC, 10);
lv_obj_set_x( ui_SHR0TC, 558 );
lv_obj_set_y( ui_SHR0TC, 129 );
lv_obj_add_flag( ui_SHR0TC, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHR0TC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHR0TC, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHR0TC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHR0TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHR0TC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHR0TC, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHR0TC, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHR0TC, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHR0TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHR0TC, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHR0TC, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHR0TC, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHR0TC, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHR0TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHR0TC, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHR0TC, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHR0TD = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHR0TD, 10);
lv_obj_set_height( ui_SHR0TD, 10);
lv_obj_set_x( ui_SHR0TD, 602 );
lv_obj_set_y( ui_SHR0TD, 145 );
lv_obj_add_flag( ui_SHR0TD, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHR0TD, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHR0TD, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHR0TD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHR0TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHR0TD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHR0TD, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHR0TD, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHR0TD, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHR0TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHR0TD, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHR0TD, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHR0TD, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHR0TD, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHR0TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHR0TD, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHR0TD, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHR1C = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHR1C, 10);
lv_obj_set_height( ui_SHR1C, 10);
lv_obj_set_x( ui_SHR1C, 558 );
lv_obj_set_y( ui_SHR1C, 145 );
lv_obj_add_flag( ui_SHR1C, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHR1C, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHR1C, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHR1C, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHR1C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHR1C, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHR1C, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHR1C, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHR1C, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHR1C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHR1C, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHR1C, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHR1C, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHR1C, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHR1C, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHR1C, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHR1C, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHR2TC = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHR2TC, 10);
lv_obj_set_height( ui_SHR2TC, 10);
lv_obj_set_x( ui_SHR2TC, 642 );
lv_obj_set_y( ui_SHR2TC, 159 );
lv_obj_add_flag( ui_SHR2TC, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHR2TC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHR2TC, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHR2TC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHR2TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHR2TC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHR2TC, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHR2TC, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHR2TC, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHR2TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHR2TC, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHR2TC, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHR2TC, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHR2TC, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHR2TC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHR2TC, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHR2TC, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SHR2TD = lv_obj_create(ui_layoutPanel);
lv_obj_set_width( ui_SHR2TD, 10);
lv_obj_set_height( ui_SHR2TD, 10);
lv_obj_set_x( ui_SHR2TD, 642 );
lv_obj_set_y( ui_SHR2TD, 178 );
lv_obj_add_flag( ui_SHR2TD, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_SHR2TD, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SHR2TD, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHR2TD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SHR2TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SHR2TD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SHR2TD, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SHR2TD, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SHR2TD, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_SHR2TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_SHR2TD, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_SHR2TD, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SHR2TD, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_SHR2TD, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_SHR2TD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_SHR2TD, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_width(ui_SHR2TD, 1, LV_PART_MAIN| LV_STATE_USER_1);

ui_SidingLabel = lv_label_create(ui_layoutPanel);
lv_obj_set_width( ui_SidingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SidingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SidingLabel, 268 );
lv_obj_set_y( ui_SidingLabel, 170 );
lv_label_set_text(ui_SidingLabel,"Siding");
lv_obj_add_flag( ui_SidingLabel, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_style_text_color(ui_SidingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SidingLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SidingLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SidingLabel, lv_color_hex(0x4F7C85), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SidingLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThrPanel = lv_obj_create(ui_Home);
lv_obj_set_width( ui_ThrPanel, 450);
lv_obj_set_height( ui_ThrPanel, 210);
lv_obj_set_x( ui_ThrPanel, 175 );
lv_obj_set_y( ui_ThrPanel, 265 );
lv_obj_add_flag( ui_ThrPanel, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( ui_ThrPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ThrPanel, lv_color_hex(0xF8EAEA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ThrPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ThrPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ThrPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ThrPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ThrPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ThrPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ThrPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ThrPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_ThrPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_ThrPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThrComp0 = ui_ThrComp_create(ui_ThrPanel);
lv_obj_set_x( ui_ThrComp0, -20 );
lv_obj_set_y( ui_ThrComp0, -20 );
lv_obj_set_align( ui_ThrComp0, LV_ALIGN_TOP_LEFT );


ui_ThrComp1 = ui_ThrComp_create(ui_ThrPanel);
lv_obj_set_x( ui_ThrComp1, 130 );
lv_obj_set_y( ui_ThrComp1, -20 );
lv_obj_set_align( ui_ThrComp1, LV_ALIGN_TOP_LEFT );

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCOTHR), lv_color_hex(0xA0FFA0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCOTHR), 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCOTHR), lv_color_hex(0x00C900), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCOTHR), 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCOTHR), lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCOTHR), 255, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCONAME), lv_color_hex(0xA0FFA0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_LOCONAME), 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_flag( ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_HORN), LV_OBJ_FLAG_CHECKABLE );   /// Flags

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_FUNCBUTTON), lv_color_hex(0xA0FFA0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp1, UI_COMP_THRCOMP_FUNCBUTTON), 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThrComp2 = ui_ThrComp_create(ui_ThrPanel);
lv_obj_set_x( ui_ThrComp2, 280 );
lv_obj_set_y( ui_ThrComp2, -20 );
lv_obj_set_align( ui_ThrComp2, LV_ALIGN_TOP_LEFT );

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCOTHR), lv_color_hex(0xA0A0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCOTHR), 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCOTHR), lv_color_hex(0x0000C9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCOTHR), 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCOTHR), lv_color_hex(0x0000FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCOTHR), 255, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCONAME), lv_color_hex(0xA0A0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCONAME), 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_flag( ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_HORN), LV_OBJ_FLAG_CHECKABLE );   /// Flags

lv_obj_set_style_bg_color(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_FUNCBUTTON), lv_color_hex(0xA0A0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_FUNCBUTTON), 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomePowerOff = lv_imgbtn_create(ui_Home);
lv_imgbtn_set_src(ui_HomePowerOff, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_power_btn_png, NULL);
lv_obj_set_width( ui_HomePowerOff, 40);
lv_obj_set_height( ui_HomePowerOff, 40);
lv_obj_set_x( ui_HomePowerOff, 743 );
lv_obj_set_y( ui_HomePowerOff, 423 );

ui_RouteBtn = lv_btn_create(ui_Home);
lv_obj_set_width( ui_RouteBtn, 82);
lv_obj_set_height( ui_RouteBtn, 35);
lv_obj_set_x( ui_RouteBtn, 682 );
lv_obj_set_y( ui_RouteBtn, 282 );
lv_obj_add_flag( ui_RouteBtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RouteBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RouteBtn, lv_color_hex(0xE1E898), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RouteBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RouteBtn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_RouteBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_RouteBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_RouteBtn, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_RouteBtn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RouteBtnLabel = lv_label_create(ui_RouteBtn);
lv_obj_set_width( ui_RouteBtnLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RouteBtnLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RouteBtnLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RouteBtnLabel,"Routes");
lv_obj_set_style_text_color(ui_RouteBtnLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RouteBtnLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RouteBtnLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DccExBtn = lv_imgbtn_create(ui_Home);
lv_imgbtn_set_src(ui_DccExBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dccex_logo_png, NULL);
lv_obj_set_width( ui_DccExBtn, 120);
lv_obj_set_height( ui_DccExBtn, 25);
lv_obj_set_x( ui_DccExBtn, 324 );
lv_obj_set_y( ui_DccExBtn, 61 );
lv_obj_set_align( ui_DccExBtn, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_DccExBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DccExBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DccExBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DccExBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DccExBtn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_DccExBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_DccExBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_DccExBtn, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_DccExBtn, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_DccExBtn, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_DccExBtn, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dccexKeyboard = lv_keyboard_create(ui_Home);
lv_keyboard_set_mode(ui_dccexKeyboard,LV_KEYBOARD_MODE_TEXT_UPPER);
lv_obj_set_width( ui_dccexKeyboard, 708);
lv_obj_set_height( ui_dccexKeyboard, 272);
lv_obj_set_x( ui_dccexKeyboard, -43 );
lv_obj_set_y( ui_dccexKeyboard, 99 );
lv_obj_set_align( ui_dccexKeyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dccexKeyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_dccexKeyboard, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dccexKeyboard, lv_color_hex(0x37758C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dccexKeyboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_dccexKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_dccexKeyboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_dccexKeyboard, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_dccexKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_dccexKeyboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_dccexKeyboard, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_dccexKeyboard, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_dccexKeyboard, lv_color_hex(0xFDFDFD), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dccexKeyboard, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_dccexKeyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dccexKeyboard, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dccexKeyboard, &lv_font_montserrat_18, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_dccexCmdText = lv_textarea_create(ui_Home);
lv_obj_set_width( ui_dccexCmdText, 298);
lv_obj_set_height( ui_dccexCmdText, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_dccexCmdText, -79 );
lv_obj_set_y( ui_dccexCmdText, -60 );
lv_obj_set_align( ui_dccexCmdText, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_dccexCmdText,"Placeholder...");
lv_textarea_set_one_line(ui_dccexCmdText,true);
lv_obj_add_flag( ui_dccexCmdText, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_bg_color(ui_dccexCmdText, lv_color_hex(0xF0F28D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dccexCmdText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_dccexCmdText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_dccexCmdText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_dccexCmdText, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_keyboardClose = lv_btn_create(ui_Home);
lv_obj_set_width( ui_keyboardClose, 68);
lv_obj_set_height( ui_keyboardClose, 50);
lv_obj_set_x( ui_keyboardClose, 711 );
lv_obj_set_y( ui_keyboardClose, 199 );
lv_obj_add_flag( ui_keyboardClose, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_keyboardClose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_keyboardClose, lv_color_hex(0x20FA2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_keyboardClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_keyboardClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_keyboardClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_keyboardClose, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_keyboardClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_keyboardClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_keyboardClose, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_keyboardClose, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CloseLabel = lv_label_create(ui_keyboardClose);
lv_obj_set_width( ui_CloseLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CloseLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CloseLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CloseLabel,"CLOSE");
lv_obj_set_style_text_color(ui_CloseLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CloseLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TurnXCSet, ui_event_TurnXCSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTL0Set, ui_event_TurnTL0Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTR0Set, ui_event_TurnTR0Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTL2Set, ui_event_TurnTL2Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTR2Set, ui_event_TurnTR2Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_comp_get_child(ui_ThrComp2, UI_COMP_THRCOMP_LOCOTHR), ui_event_ThrComp2_LocoThr, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HomePowerOff, ui_event_HomePowerOff, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RouteBtn, ui_event_RouteBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DccExBtn, ui_event_DccExBtn, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_dccexKeyboard,ui_dccexCmdText);
lv_obj_add_event_cb(ui_dccexKeyboard, ui_event_dccexKeyboard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_keyboardClose, ui_event_keyboardClose, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
   if (ui_Home) lv_obj_del(ui_Home);

// NULL screen variables
ui_Home= NULL;
ui_Logo= NULL;
ui_MainTitle= NULL;
ui_WifiLevel= NULL;
ui_WifiLabel= NULL;
ui_layoutPanel= NULL;
ui_OutLoop0= NULL;
ui_OutLoopLabelB= NULL;
ui_OutLoop1= NULL;
ui_OutLoopLabelA= NULL;
ui_TownLoop= NULL;
ui_TownLoopLabel= NULL;
ui_Siding= NULL;
ui_TurnXCSet= NULL;
ui_TurnTL0Set= NULL;
ui_TurnTR0Set= NULL;
ui_TurnTL2Set= NULL;
ui_TurnTR2Set= NULL;
ui_SHL0C= NULL;
ui_SHL1TD= NULL;
ui_SHL1TC= NULL;
ui_SHL2C= NULL;
ui_SHL2D= NULL;
ui_SHR0TC= NULL;
ui_SHR0TD= NULL;
ui_SHR1C= NULL;
ui_SHR2TC= NULL;
ui_SHR2TD= NULL;
ui_SidingLabel= NULL;
ui_ThrPanel= NULL;
ui_ThrComp0= NULL;
ui_ThrComp1= NULL;
ui_ThrComp2= NULL;
ui_HomePowerOff= NULL;
ui_RouteBtn= NULL;
ui_RouteBtnLabel= NULL;
ui_DccExBtn= NULL;
ui_dccexKeyboard= NULL;
ui_dccexCmdText= NULL;
ui_keyboardClose= NULL;
ui_CloseLabel= NULL;

}
