// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_Logo;
extern lv_obj_t *ui_MainTitle;
extern lv_obj_t *ui_WifiLevel;
extern lv_obj_t *ui_WifiLabel;
extern lv_obj_t *ui_layoutPanel;
extern lv_obj_t *ui_OutLoop0;
extern lv_obj_t *ui_OutLoopLabelB;
extern lv_obj_t *ui_OutLoop1;
extern lv_obj_t *ui_OutLoopLabelA;
extern lv_obj_t *ui_TownLoop;
extern lv_obj_t *ui_TownLoopLabel;
extern lv_obj_t *ui_Siding;
extern void ui_event_TurnXCSet( lv_event_t * e);
extern lv_obj_t *ui_TurnXCSet;
extern void ui_event_TurnTL0Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTL0Set;
extern void ui_event_TurnTR0Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTR0Set;
extern void ui_event_TurnTL2Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTL2Set;
extern void ui_event_TurnTR2Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTR2Set;
extern lv_obj_t *ui_SHL0C;
extern lv_obj_t *ui_SHL1TD;
extern lv_obj_t *ui_SHL1TC;
extern lv_obj_t *ui_SHL2C;
extern lv_obj_t *ui_SHL2D;
extern lv_obj_t *ui_SHR0TC;
extern lv_obj_t *ui_SHR0TD;
extern lv_obj_t *ui_SHR1C;
extern lv_obj_t *ui_SHR2TC;
extern lv_obj_t *ui_SHR2TD;
extern lv_obj_t *ui_SidingLabel;
extern lv_obj_t *ui_ThrPanel;
extern lv_obj_t *ui_ThrComp0;
extern lv_obj_t *ui_ThrComp1;
extern lv_obj_t *ui_ThrComp2;
extern void ui_event_ThrComp2_LocoThr( lv_event_t * e);
extern void ui_event_HomePowerOff( lv_event_t * e);
extern lv_obj_t *ui_HomePowerOff;
extern void ui_event_RouteBtn( lv_event_t * e);
extern lv_obj_t *ui_RouteBtn;
extern lv_obj_t *ui_RouteBtnLabel;
extern void ui_event_DccExBtn( lv_event_t * e);
extern lv_obj_t *ui_DccExBtn;
extern void ui_event_dccexKeyboard( lv_event_t * e);
extern lv_obj_t *ui_dccexKeyboard;
extern lv_obj_t *ui_dccexCmdText;
extern void ui_event_keyboardClose( lv_event_t * e);
extern lv_obj_t *ui_keyboardClose;
extern lv_obj_t *ui_CloseLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

