// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#include "ui.h"

lv_obj_t *uic_LocoThr0;
lv_obj_t *ui_Home = NULL;lv_obj_t *ui_Logo = NULL;lv_obj_t *ui_WifiLevel = NULL;lv_obj_t *ui_WifiLabel = NULL;lv_obj_t *ui_layoutPanel = NULL;lv_obj_t *ui_OutLoop0 = NULL;lv_obj_t *ui_OutLoopLabelB = NULL;lv_obj_t *ui_OutLoop1 = NULL;lv_obj_t *ui_OutLoopLabelA = NULL;lv_obj_t *ui_TownLoop = NULL;lv_obj_t *ui_TownLoopLabel = NULL;lv_obj_t *ui_Siding = NULL;lv_obj_t *ui_TurnXCSet = NULL;lv_obj_t *ui_TurnTL0Set = NULL;lv_obj_t *ui_TurnTR0Set = NULL;lv_obj_t *ui_TurnTL2Set = NULL;lv_obj_t *ui_TurnTR2Set = NULL;lv_obj_t *ui_SidingLabel = NULL;lv_obj_t *ui_ThrPanel = NULL;lv_obj_t *ui_LocoThr0 = NULL;lv_obj_t *ui_LocoThr1 = NULL;lv_obj_t *ui_LocoThr2 = NULL;lv_obj_t *ui_LocoRev0 = NULL;lv_obj_t *ui_LocoRev1 = NULL;lv_obj_t *ui_LocoRev2 = NULL;lv_obj_t *ui_LocoSpeed0 = NULL;lv_obj_t *ui_LocoSpeed1 = NULL;lv_obj_t *ui_LocoSpeed2 = NULL;lv_obj_t *ui_LocoName0 = NULL;lv_obj_t *ui_LocoName1 = NULL;lv_obj_t *ui_LocoName2 = NULL;lv_obj_t *ui_FuncButton0 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_FuncButton1 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_FuncButton2 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_horn0 = NULL;lv_obj_t *ui_horn1 = NULL;lv_obj_t *ui_horn2 = NULL;lv_obj_t *ui_RosterBtn = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_RouteBtn1 = NULL;lv_obj_t *ui_RouteBtn = NULL;lv_obj_t *ui_RosterDisplay = NULL;lv_obj_t *ui_RosterList = NULL;lv_obj_t *ui_RosterClose = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_funcPanel = NULL;lv_obj_t *ui_HeadLightF1 = NULL;lv_obj_t *ui_Func2Label = NULL;lv_obj_t *ui_CouplerF3 = NULL;lv_obj_t *ui_Func3Label = NULL;lv_obj_t *ui_FlangeF7 = NULL;lv_obj_t *ui_Func7Label = NULL;lv_obj_t *ui_MasterSoundF8 = NULL;lv_obj_t *ui_RadiatorF11 = NULL;lv_obj_t *ui_Func11Label = NULL;lv_obj_t *ui_FuncPanelClose = NULL;lv_obj_t *ui_FuncCloseLabel = NULL;
// event funtions
void ui_event_TurnXCSet( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTL0Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTR0Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTL2Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_TurnTR2Set( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setTurnOut( e );
}
}

void ui_event_LocoThr0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoSpeed( e );
      _ui_slider_set_text_value( ui_LocoSpeed0, target, "", "");
}
}

void ui_event_LocoThr1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoSpeed( e );
      _ui_slider_set_text_value( ui_LocoSpeed1, target, "", "");
}
}

void ui_event_LocoThr2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoSpeed( e );
      _ui_slider_set_text_value( ui_LocoSpeed2, target, "", "");
}
}

void ui_event_LocoRev0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocReverse( e );
}
}

void ui_event_LocoRev1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocReverse( e );
}
}

void ui_event_LocoRev2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocReverse( e );
}
}

void ui_event_FuncButton0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      openLocoFunc( e );
      _ui_flag_modify( ui_funcPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_FuncButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      openLocoFunc( e );
      _ui_flag_modify( ui_funcPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_FuncButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      openLocoFunc( e );
      _ui_flag_modify( ui_funcPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_horn0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoHorn( e );
}
}

void ui_event_horn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoHorn( e );
}
}

void ui_event_horn2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoHorn( e );
}
}

void ui_event_RosterBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      showLocoRoster( e );
      _ui_flag_modify( ui_RosterDisplay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_RouteBtn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      showRoutes( e );
}
}

void ui_event_RouteBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      showTrainRoutes( e );
}
}

void ui_event_HeadLightF1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc( e );
}
}

void ui_event_CouplerF3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc( e );
}
}

void ui_event_FlangeF7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc( e );
}
}

void ui_event_MasterSoundF8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setLocoFunc( e );
}
}

void ui_event_RadiatorF11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc( e );
}
}

void ui_event_FuncPanelClose( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setLocoFunc( e );
}
}

// build funtions

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Home, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Home, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Home, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Logo = lv_img_create(ui_Home);
lv_img_set_src(ui_Logo, &ui_img_vthrottle_logo_png);
lv_obj_set_width( ui_Logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Logo, -257 );
lv_obj_set_y( ui_Logo, 175 );
lv_obj_set_align( ui_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Logo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WifiLevel = lv_bar_create(ui_Home);
lv_bar_set_value(ui_WifiLevel,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_WifiLevel, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_WifiLevel, 80);
lv_obj_set_height( ui_WifiLevel, 10);
lv_obj_set_x( ui_WifiLevel, 110 );
lv_obj_set_y( ui_WifiLevel, 13 );
lv_obj_set_style_bg_color(ui_WifiLevel, lv_color_hex(0x97CFCD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiLevel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_WifiLevel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_WifiLevel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_WifiLevel, lv_color_hex(0x3334FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiLevel, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_WifiLabel = lv_label_create(ui_Home);
lv_obj_set_width( ui_WifiLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiLabel, 67 );
lv_obj_set_y( ui_WifiLabel, -222 );
lv_obj_set_align( ui_WifiLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_WifiLabel,"Wifi:");

ui_layoutPanel = lv_obj_create(ui_Home);
lv_obj_set_width( ui_layoutPanel, 610);
lv_obj_set_height( ui_layoutPanel, 230);
lv_obj_set_x( ui_layoutPanel, 96 );
lv_obj_set_y( ui_layoutPanel, 30 );
lv_obj_clear_flag( ui_layoutPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_layoutPanel, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_layoutPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoop0 = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_OutLoop0);
lv_obj_set_width( ui_OutLoop0, 580);
lv_obj_set_height( ui_OutLoop0, 180);
lv_obj_set_x( ui_OutLoop0, -7 );
lv_obj_set_y( ui_OutLoop0, -6 );
lv_obj_clear_flag( ui_OutLoop0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_OutLoop0, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OutLoop0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OutLoop0, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoopLabelB = lv_label_create(ui_OutLoop0);
lv_obj_set_width( ui_OutLoopLabelB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OutLoopLabelB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutLoopLabelB, 78 );
lv_obj_set_y( ui_OutLoopLabelB, 81 );
lv_obj_set_align( ui_OutLoopLabelB, LV_ALIGN_CENTER );
lv_label_set_text(ui_OutLoopLabelB,"Out Loop B");
lv_obj_set_style_text_color(ui_OutLoopLabelB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OutLoopLabelB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OutLoopLabelB, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutLoopLabelB, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutLoopLabelB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoop1 = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_OutLoop1);
lv_obj_set_width( ui_OutLoop1, 550);
lv_obj_set_height( ui_OutLoop1, 150);
lv_obj_set_x( ui_OutLoop1, 8 );
lv_obj_set_y( ui_OutLoop1, 9 );
lv_obj_clear_flag( ui_OutLoop1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_OutLoop1, lv_color_hex(0xFFB464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OutLoop1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OutLoop1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutLoopLabelA = lv_label_create(ui_OutLoop1);
lv_obj_set_width( ui_OutLoopLabelA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OutLoopLabelA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutLoopLabelA, 13 );
lv_obj_set_y( ui_OutLoopLabelA, 65 );
lv_obj_set_align( ui_OutLoopLabelA, LV_ALIGN_CENTER );
lv_label_set_text(ui_OutLoopLabelA,"Out Loop A");
lv_obj_set_style_text_color(ui_OutLoopLabelA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OutLoopLabelA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OutLoopLabelA, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutLoopLabelA, lv_color_hex(0xFFB4C4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutLoopLabelA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TownLoop = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_TownLoop);
lv_obj_set_width( ui_TownLoop, 500);
lv_obj_set_height( ui_TownLoop, 80);
lv_obj_set_x( ui_TownLoop, 31 );
lv_obj_set_y( ui_TownLoop, 64 );
lv_obj_clear_flag( ui_TownLoop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_TownLoop, lv_color_hex(0xC10000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TownLoop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TownLoop, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TownLoopLabel = lv_label_create(ui_TownLoop);
lv_obj_set_width( ui_TownLoopLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TownLoopLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TownLoopLabel, -54 );
lv_obj_set_y( ui_TownLoopLabel, 29 );
lv_obj_set_align( ui_TownLoopLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TownLoopLabel,"Town  Loop");
lv_obj_set_style_text_color(ui_TownLoopLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TownLoopLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TownLoopLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TownLoopLabel, lv_color_hex(0xC10000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TownLoopLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Siding = lv_obj_create(ui_layoutPanel);
lv_obj_remove_style_all(ui_Siding);
lv_obj_set_width( ui_Siding, 400);
lv_obj_set_height( ui_Siding, 5);
lv_obj_set_x( ui_Siding, 90 );
lv_obj_set_y( ui_Siding, 184 );
lv_obj_clear_flag( ui_Siding, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Siding, lv_color_hex(0x4F7C85), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Siding, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Siding, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnXCSet = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_xc_png, NULL);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_tunrout_xc1_png, NULL);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_xc_png, NULL);
lv_imgbtn_set_src(ui_TurnXCSet, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_tunrout_xc1_png, NULL);
lv_obj_set_width( ui_TurnXCSet, 30);
lv_obj_set_height( ui_TurnXCSet, 30);
lv_obj_set_x( ui_TurnXCSet, 275 );
lv_obj_set_y( ui_TurnXCSet, -11 );
lv_obj_add_flag( ui_TurnXCSet, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_TurnTL0Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tl0_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL0Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tl0_1_png, NULL);
lv_obj_set_width( ui_TurnTL0Set, 30);
lv_obj_set_height( ui_TurnTL0Set, 30);
lv_obj_set_x( ui_TurnTL0Set, 100 );
lv_obj_set_y( ui_TurnTL0Set, 135 );
lv_obj_add_flag( ui_TurnTL0Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTL0Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTL0Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTL0Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnTR0Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tr0_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl0_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR0Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tr0_1_png, NULL);
lv_obj_set_width( ui_TurnTR0Set, 30);
lv_obj_set_height( ui_TurnTR0Set, 30);
lv_obj_set_x( ui_TurnTR0Set, 450 );
lv_obj_set_y( ui_TurnTR0Set, 135 );
lv_obj_add_flag( ui_TurnTR0Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTR0Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTR0Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTR0Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnTL2Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tl2_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTL2Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tl2_1_png, NULL);
lv_obj_set_width( ui_TurnTL2Set, 30);
lv_obj_set_height( ui_TurnTL2Set, 30);
lv_obj_set_x( ui_TurnTL2Set, 60 );
lv_obj_set_y( ui_TurnTL2Set, 164 );
lv_obj_add_flag( ui_TurnTL2Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTL2Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTL2Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTL2Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TurnTR2Set = lv_imgbtn_create(ui_layoutPanel);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_turnout_tr2_1_png, NULL);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_turnout_tl2_0_png, NULL);
lv_imgbtn_set_src(ui_TurnTR2Set, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_turnout_tr2_1_png, NULL);
lv_obj_set_width( ui_TurnTR2Set, 30);
lv_obj_set_height( ui_TurnTR2Set, 30);
lv_obj_set_x( ui_TurnTR2Set, 490 );
lv_obj_set_y( ui_TurnTR2Set, 164 );
lv_obj_add_flag( ui_TurnTR2Set, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_img_src( ui_TurnTR2Set, &ui_img_turnout_xc_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_TurnTR2Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TurnTR2Set, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SidingLabel = lv_label_create(ui_Home);
lv_obj_set_width( ui_SidingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SidingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SidingLabel, -42 );
lv_obj_set_y( ui_SidingLabel, -4 );
lv_obj_set_align( ui_SidingLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SidingLabel,"Siding");
lv_obj_add_flag( ui_SidingLabel, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_style_text_color(ui_SidingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SidingLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SidingLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SidingLabel, lv_color_hex(0x4F7C85), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SidingLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThrPanel = lv_obj_create(ui_Home);
lv_obj_set_width( ui_ThrPanel, 330);
lv_obj_set_height( ui_ThrPanel, 210);
lv_obj_set_x( ui_ThrPanel, 375 );
lv_obj_set_y( ui_ThrPanel, 265 );
lv_obj_clear_flag( ui_ThrPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ThrPanel, lv_color_hex(0xFCCACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ThrPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LocoThr0 = lv_slider_create(ui_ThrPanel);
lv_slider_set_range(ui_LocoThr0, 0,128);
lv_slider_set_value( ui_LocoThr0, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LocoThr0)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LocoThr0, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LocoThr0, 10);
lv_obj_set_height( ui_LocoThr0, 150);
lv_obj_set_x( ui_LocoThr0, 50 );
lv_obj_set_y( ui_LocoThr0, 0 );
lv_obj_set_style_bg_color(ui_LocoThr0, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoThr0, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LocoThr0, lv_color_hex(0xC90000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr0, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LocoThr0, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr0, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LocoThr0, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LocoThr0, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoThr0, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LocoThr1 = lv_slider_create(ui_ThrPanel);
lv_slider_set_range(ui_LocoThr1, 0,128);
lv_slider_set_value( ui_LocoThr1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LocoThr1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LocoThr1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LocoThr1, 10);
lv_obj_set_height( ui_LocoThr1, 150);
lv_obj_set_x( ui_LocoThr1, 150 );
lv_obj_set_y( ui_LocoThr1, 0 );
lv_obj_set_style_bg_color(ui_LocoThr1, lv_color_hex(0xA0FFA0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoThr1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LocoThr1, lv_color_hex(0x00C900), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LocoThr1, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LocoThr1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LocoThr1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoThr1, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LocoThr2 = lv_slider_create(ui_ThrPanel);
lv_slider_set_range(ui_LocoThr2, 0,128);
lv_slider_set_value( ui_LocoThr2, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LocoThr2)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LocoThr2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LocoThr2, 10);
lv_obj_set_height( ui_LocoThr2, 150);
lv_obj_set_x( ui_LocoThr2, 250 );
lv_obj_set_y( ui_LocoThr2, 0 );
lv_obj_set_style_bg_color(ui_LocoThr2, lv_color_hex(0xA0A0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoThr2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LocoThr2, lv_color_hex(0x0000C9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LocoThr2, lv_color_hex(0x0000FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoThr2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LocoThr2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LocoThr2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoThr2, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LocoRev0 = lv_imgbtn_create(ui_ThrPanel);
lv_imgbtn_set_src(ui_LocoRev0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(ui_LocoRev0, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_loco_rev_png, NULL);
lv_imgbtn_set_src(ui_LocoRev0, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(ui_LocoRev0, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_loco_rev_png, NULL);
lv_obj_set_width( ui_LocoRev0, 40);
lv_obj_set_height( ui_LocoRev0, 40);
lv_obj_set_x( ui_LocoRev0, -5 );
lv_obj_set_y( ui_LocoRev0, 60 );
lv_obj_add_flag( ui_LocoRev0, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_LocoRev1 = lv_imgbtn_create(ui_ThrPanel);
lv_imgbtn_set_src(ui_LocoRev1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(ui_LocoRev1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_loco_rev_png, NULL);
lv_imgbtn_set_src(ui_LocoRev1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(ui_LocoRev1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_loco_rev_png, NULL);
lv_obj_set_width( ui_LocoRev1, 40);
lv_obj_set_height( ui_LocoRev1, 40);
lv_obj_set_x( ui_LocoRev1, 95 );
lv_obj_set_y( ui_LocoRev1, 60 );
lv_obj_add_flag( ui_LocoRev1, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_LocoRev2 = lv_imgbtn_create(ui_ThrPanel);
lv_imgbtn_set_src(ui_LocoRev2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(ui_LocoRev2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_loco_rev_png, NULL);
lv_imgbtn_set_src(ui_LocoRev2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_loco_fwd_png, NULL);
lv_imgbtn_set_src(ui_LocoRev2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_loco_rev_png, NULL);
lv_obj_set_width( ui_LocoRev2, 40);
lv_obj_set_height( ui_LocoRev2, 40);
lv_obj_set_x( ui_LocoRev2, 195 );
lv_obj_set_y( ui_LocoRev2, 60 );
lv_obj_add_flag( ui_LocoRev2, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_LocoSpeed0 = lv_label_create(ui_ThrPanel);
lv_obj_set_width( ui_LocoSpeed0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LocoSpeed0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LocoSpeed0, 46 );
lv_obj_set_y( ui_LocoSpeed0, -20 );
lv_label_set_text(ui_LocoSpeed0,"0");
lv_obj_set_style_text_color(ui_LocoSpeed0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LocoSpeed0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LocoSpeed0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LocoSpeed0, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LocoSpeed1 = lv_label_create(ui_ThrPanel);
lv_obj_set_width( ui_LocoSpeed1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LocoSpeed1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LocoSpeed1, 145 );
lv_obj_set_y( ui_LocoSpeed1, -20 );
lv_label_set_text(ui_LocoSpeed1,"0");
lv_obj_set_style_text_color(ui_LocoSpeed1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LocoSpeed1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LocoSpeed1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LocoSpeed1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LocoSpeed2 = lv_label_create(ui_ThrPanel);
lv_obj_set_width( ui_LocoSpeed2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LocoSpeed2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LocoSpeed2, 245 );
lv_obj_set_y( ui_LocoSpeed2, -20 );
lv_label_set_text(ui_LocoSpeed2,"0");
lv_obj_set_style_text_color(ui_LocoSpeed2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LocoSpeed2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LocoSpeed2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LocoSpeed2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LocoName0 = lv_label_create(ui_ThrPanel);
lv_obj_set_width( ui_LocoName0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LocoName0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LocoName0, 25 );
lv_obj_set_y( ui_LocoName0, 165 );
lv_label_set_text(ui_LocoName0,"Loco 0");
lv_obj_set_style_text_color(ui_LocoName0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LocoName0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LocoName0, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LocoName0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoName0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoName0, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LocoName1 = lv_label_create(ui_ThrPanel);
lv_obj_set_width( ui_LocoName1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LocoName1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LocoName1, 125 );
lv_obj_set_y( ui_LocoName1, 165 );
lv_label_set_text(ui_LocoName1,"Loco 1");
lv_obj_set_style_text_color(ui_LocoName1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LocoName1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LocoName1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LocoName1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoName1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoName1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LocoName2 = lv_label_create(ui_ThrPanel);
lv_obj_set_width( ui_LocoName2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LocoName2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LocoName2, 225 );
lv_obj_set_y( ui_LocoName2, 165 );
lv_label_set_text(ui_LocoName2,"Loco2");
lv_obj_set_style_text_color(ui_LocoName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LocoName2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LocoName2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LocoName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LocoName2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LocoName2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuncButton0 = lv_btn_create(ui_ThrPanel);
lv_obj_set_width( ui_FuncButton0, 40);
lv_obj_set_height( ui_FuncButton0, 40);
lv_obj_set_x( ui_FuncButton0, -5 );
lv_obj_set_y( ui_FuncButton0, 0 );
lv_obj_add_flag( ui_FuncButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FuncButton0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FuncButton0, lv_color_hex(0xFFA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FuncButton0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FuncButton0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FuncButton0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_FuncButton0, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_FuncButton0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FuncButton0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_FuncButton0, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_FuncButton0, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_FuncButton0);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Fn");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuncButton1 = lv_btn_create(ui_ThrPanel);
lv_obj_set_width( ui_FuncButton1, 40);
lv_obj_set_height( ui_FuncButton1, 40);
lv_obj_set_x( ui_FuncButton1, 95 );
lv_obj_set_y( ui_FuncButton1, 0 );
lv_obj_add_flag( ui_FuncButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FuncButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FuncButton1, lv_color_hex(0xA0FFA0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FuncButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FuncButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FuncButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_FuncButton1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_FuncButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FuncButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_FuncButton1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_FuncButton1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_FuncButton1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Fn");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuncButton2 = lv_btn_create(ui_ThrPanel);
lv_obj_set_width( ui_FuncButton2, 40);
lv_obj_set_height( ui_FuncButton2, 40);
lv_obj_set_x( ui_FuncButton2, 195 );
lv_obj_set_y( ui_FuncButton2, 0 );
lv_obj_add_flag( ui_FuncButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FuncButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FuncButton2, lv_color_hex(0xA0A0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FuncButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FuncButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FuncButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_FuncButton2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_FuncButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FuncButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_FuncButton2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_FuncButton2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_FuncButton2);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Fn");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_horn0 = lv_imgbtn_create(ui_ThrPanel);
lv_imgbtn_set_src(ui_horn0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_horn_png, NULL);
lv_imgbtn_set_src(ui_horn0, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sound_wave_png, NULL);
lv_obj_set_width( ui_horn0, 32);
lv_obj_set_height( ui_horn0, 32);
lv_obj_set_x( ui_horn0, 0 );
lv_obj_set_y( ui_horn0, 105 );

ui_horn1 = lv_imgbtn_create(ui_ThrPanel);
lv_imgbtn_set_src(ui_horn1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_horn_png, NULL);
lv_imgbtn_set_src(ui_horn1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sound_wave_png, NULL);
lv_obj_set_width( ui_horn1, 32);
lv_obj_set_height( ui_horn1, 32);
lv_obj_set_x( ui_horn1, 95 );
lv_obj_set_y( ui_horn1, 105 );

ui_horn2 = lv_imgbtn_create(ui_ThrPanel);
lv_imgbtn_set_src(ui_horn2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_horn_png, NULL);
lv_imgbtn_set_src(ui_horn2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sound_wave_png, NULL);
lv_obj_set_width( ui_horn2, 32);
lv_obj_set_height( ui_horn2, 32);
lv_obj_set_x( ui_horn2, 195 );
lv_obj_set_y( ui_horn2, 105 );

ui_RosterBtn = lv_btn_create(ui_Home);
lv_obj_set_width( ui_RosterBtn, 82);
lv_obj_set_height( ui_RosterBtn, 35);
lv_obj_set_x( ui_RosterBtn, 280 );
lv_obj_set_y( ui_RosterBtn, 280 );
lv_obj_add_flag( ui_RosterBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RosterBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RosterBtn, lv_color_hex(0x9EF7F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RosterBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RosterBtn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_RosterBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_RosterBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_RosterBtn, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_RosterBtn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_RosterBtn);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Roster");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RouteBtn1 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_RouteBtn1, 82);
lv_obj_set_height( ui_RouteBtn1, 35);
lv_obj_set_x( ui_RouteBtn1, 280 );
lv_obj_set_y( ui_RouteBtn1, 330 );
lv_obj_add_flag( ui_RouteBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RouteBtn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RouteBtn1, lv_color_hex(0xE1E898), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RouteBtn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RouteBtn1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_RouteBtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_RouteBtn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_RouteBtn1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_RouteBtn1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RouteBtn = lv_label_create(ui_RouteBtn1);
lv_obj_set_width( ui_RouteBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RouteBtn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RouteBtn, LV_ALIGN_CENTER );
lv_label_set_text(ui_RouteBtn,"Routes");
lv_obj_set_style_text_color(ui_RouteBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RouteBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RosterDisplay = lv_obj_create(ui_Home);
lv_obj_set_width( ui_RosterDisplay, 250);
lv_obj_set_height( ui_RosterDisplay, 145);
lv_obj_set_x( ui_RosterDisplay, 100 );
lv_obj_set_y( ui_RosterDisplay, 264 );
lv_obj_add_flag( ui_RosterDisplay, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_RosterDisplay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RosterDisplay, lv_color_hex(0xE9FACD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RosterDisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RosterDisplay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RosterDisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RosterDisplay, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RosterList = lv_textarea_create(ui_RosterDisplay);
lv_obj_set_width( ui_RosterList, 220);
lv_obj_set_height( ui_RosterList, 90);
lv_obj_set_x( ui_RosterList, -10 );
lv_obj_set_y( ui_RosterList, -10 );
lv_textarea_set_max_length(ui_RosterList,400);
lv_textarea_set_text(ui_RosterList,"Loco Roster");
lv_textarea_set_placeholder_text(ui_RosterList,"Placeholder...");
lv_obj_set_style_bg_color(ui_RosterList, lv_color_hex(0xCCC7C7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RosterList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RosterList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RosterList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RosterList, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RosterClose = lv_btn_create(ui_RosterDisplay);
lv_obj_set_width( ui_RosterClose, 55);
lv_obj_set_height( ui_RosterClose, 25);
lv_obj_set_x( ui_RosterClose, 80 );
lv_obj_set_y( ui_RosterClose, 50 );
lv_obj_set_align( ui_RosterClose, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RosterClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RosterClose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RosterClose, lv_color_hex(0xDCFBD8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RosterClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RosterClose, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_RosterClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_RosterClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_RosterClose, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_RosterClose, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_RosterClose);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Close");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_funcPanel = lv_obj_create(ui_Home);
lv_obj_set_width( ui_funcPanel, 184);
lv_obj_set_height( ui_funcPanel, 154);
lv_obj_set_x( ui_funcPanel, 180 );
lv_obj_set_y( ui_funcPanel, 279 );
lv_obj_add_flag( ui_funcPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_funcPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_funcPanel, lv_color_hex(0xE1DFA5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_funcPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_funcPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_funcPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeadLightF1 = lv_btn_create(ui_funcPanel);
lv_obj_set_width( ui_HeadLightF1, 74);
lv_obj_set_height( ui_HeadLightF1, 20);
lv_obj_set_x( ui_HeadLightF1, -9 );
lv_obj_set_y( ui_HeadLightF1, -11 );
lv_obj_add_state( ui_HeadLightF1, LV_STATE_USER_4 );     /// States
lv_obj_add_flag( ui_HeadLightF1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeadLightF1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeadLightF1, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadLightF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeadLightF1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadLightF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HeadLightF1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_HeadLightF1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeadLightF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_HeadLightF1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_HeadLightF1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadLightF1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadLightF1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Func2Label = lv_label_create(ui_HeadLightF1);
lv_obj_set_width( ui_Func2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Func2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Func2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Func2Label,"Head Light");
lv_obj_set_style_text_color(ui_Func2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Func2Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Func2Label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CouplerF3 = lv_btn_create(ui_funcPanel);
lv_obj_set_width( ui_CouplerF3, 74);
lv_obj_set_height( ui_CouplerF3, 20);
lv_obj_set_x( ui_CouplerF3, 76 );
lv_obj_set_y( ui_CouplerF3, -11 );
lv_obj_add_flag( ui_CouplerF3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CouplerF3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CouplerF3, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CouplerF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CouplerF3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CouplerF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CouplerF3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_CouplerF3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_CouplerF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_CouplerF3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_CouplerF3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Func3Label = lv_label_create(ui_CouplerF3);
lv_obj_set_width( ui_Func3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Func3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Func3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Func3Label,"Coupler");
lv_obj_set_style_text_color(ui_Func3Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Func3Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Func3Label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FlangeF7 = lv_btn_create(ui_funcPanel);
lv_obj_set_width( ui_FlangeF7, 74);
lv_obj_set_height( ui_FlangeF7, 20);
lv_obj_set_x( ui_FlangeF7, -9 );
lv_obj_set_y( ui_FlangeF7, 22 );
lv_obj_add_flag( ui_FlangeF7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FlangeF7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FlangeF7, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FlangeF7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FlangeF7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FlangeF7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_FlangeF7, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_FlangeF7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FlangeF7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_FlangeF7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_FlangeF7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Func7Label = lv_label_create(ui_FlangeF7);
lv_obj_set_width( ui_Func7Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Func7Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Func7Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Func7Label,"Flange");
lv_obj_set_style_text_color(ui_Func7Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Func7Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Func7Label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MasterSoundF8 = lv_imgbtn_create(ui_funcPanel);
lv_imgbtn_set_src(ui_MasterSoundF8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sound_png, NULL);
lv_imgbtn_set_src(ui_MasterSoundF8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sound_off_png, NULL);
lv_imgbtn_set_src(ui_MasterSoundF8, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_sound_png, NULL);
lv_imgbtn_set_src(ui_MasterSoundF8, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_sound_off_png, NULL);
lv_obj_set_width( ui_MasterSoundF8, 30);
lv_obj_set_height( ui_MasterSoundF8, 30);
lv_obj_set_x( ui_MasterSoundF8, -1 );
lv_obj_set_y( ui_MasterSoundF8, 90 );
lv_obj_add_flag( ui_MasterSoundF8, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_RadiatorF11 = lv_btn_create(ui_funcPanel);
lv_obj_set_width( ui_RadiatorF11, 74);
lv_obj_set_height( ui_RadiatorF11, 20);
lv_obj_set_x( ui_RadiatorF11, 74 );
lv_obj_set_y( ui_RadiatorF11, 22 );
lv_obj_add_flag( ui_RadiatorF11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RadiatorF11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RadiatorF11, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RadiatorF11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RadiatorF11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RadiatorF11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RadiatorF11, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_RadiatorF11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_RadiatorF11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_RadiatorF11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_RadiatorF11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Func11Label = lv_label_create(ui_RadiatorF11);
lv_obj_set_width( ui_Func11Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Func11Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Func11Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Func11Label,"Radiator");
lv_obj_set_style_text_color(ui_Func11Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Func11Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Func11Label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuncPanelClose = lv_btn_create(ui_funcPanel);
lv_obj_set_width( ui_FuncPanelClose, 60);
lv_obj_set_height( ui_FuncPanelClose, 20);
lv_obj_set_x( ui_FuncPanelClose, 85 );
lv_obj_set_y( ui_FuncPanelClose, 100 );
lv_obj_add_flag( ui_FuncPanelClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FuncPanelClose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FuncPanelClose, lv_color_hex(0x76F658), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FuncPanelClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FuncPanelClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FuncPanelClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_FuncPanelClose, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_FuncPanelClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FuncPanelClose, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_FuncPanelClose, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_FuncPanelClose, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuncCloseLabel = lv_label_create(ui_FuncPanelClose);
lv_obj_set_width( ui_FuncCloseLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuncCloseLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_FuncCloseLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuncCloseLabel,"Close");
lv_obj_set_style_text_color(ui_FuncCloseLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FuncCloseLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FuncCloseLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TurnXCSet, ui_event_TurnXCSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTL0Set, ui_event_TurnTL0Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTR0Set, ui_event_TurnTR0Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTL2Set, ui_event_TurnTL2Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TurnTR2Set, ui_event_TurnTR2Set, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LocoThr0, ui_event_LocoThr0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LocoThr1, ui_event_LocoThr1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LocoThr2, ui_event_LocoThr2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LocoRev0, ui_event_LocoRev0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LocoRev1, ui_event_LocoRev1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LocoRev2, ui_event_LocoRev2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FuncButton0, ui_event_FuncButton0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FuncButton1, ui_event_FuncButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FuncButton2, ui_event_FuncButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_horn0, ui_event_horn0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_horn1, ui_event_horn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_horn2, ui_event_horn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RosterBtn, ui_event_RosterBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RouteBtn, ui_event_RouteBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RouteBtn1, ui_event_RouteBtn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeadLightF1, ui_event_HeadLightF1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CouplerF3, ui_event_CouplerF3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FlangeF7, ui_event_FlangeF7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MasterSoundF8, ui_event_MasterSoundF8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RadiatorF11, ui_event_RadiatorF11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FuncPanelClose, ui_event_FuncPanelClose, LV_EVENT_ALL, NULL);
uic_LocoThr0 = ui_LocoThr0;

}

void ui_Home_screen_destroy(void)
{
   if (ui_Home) lv_obj_del(ui_Home);

// NULL screen variables
ui_Home= NULL;
ui_Logo= NULL;
ui_WifiLevel= NULL;
ui_WifiLabel= NULL;
ui_layoutPanel= NULL;
ui_OutLoop0= NULL;
ui_OutLoopLabelB= NULL;
ui_OutLoop1= NULL;
ui_OutLoopLabelA= NULL;
ui_TownLoop= NULL;
ui_TownLoopLabel= NULL;
ui_Siding= NULL;
ui_TurnXCSet= NULL;
ui_TurnTL0Set= NULL;
ui_TurnTR0Set= NULL;
ui_TurnTL2Set= NULL;
ui_TurnTR2Set= NULL;
ui_SidingLabel= NULL;
ui_ThrPanel= NULL;
uic_LocoThr0= NULL;
ui_LocoThr0= NULL;
ui_LocoThr1= NULL;
ui_LocoThr2= NULL;
ui_LocoRev0= NULL;
ui_LocoRev1= NULL;
ui_LocoRev2= NULL;
ui_LocoSpeed0= NULL;
ui_LocoSpeed1= NULL;
ui_LocoSpeed2= NULL;
ui_LocoName0= NULL;
ui_LocoName1= NULL;
ui_LocoName2= NULL;
ui_FuncButton0= NULL;
ui_Label2= NULL;
ui_FuncButton1= NULL;
ui_Label4= NULL;
ui_FuncButton2= NULL;
ui_Label5= NULL;
ui_horn0= NULL;
ui_horn1= NULL;
ui_horn2= NULL;
ui_RosterBtn= NULL;
ui_Label1= NULL;
ui_RouteBtn1= NULL;
ui_RouteBtn= NULL;
ui_RosterDisplay= NULL;
ui_RosterList= NULL;
ui_RosterClose= NULL;
ui_Label3= NULL;
ui_funcPanel= NULL;
ui_HeadLightF1= NULL;
ui_Func2Label= NULL;
ui_CouplerF3= NULL;
ui_Func3Label= NULL;
ui_FlangeF7= NULL;
ui_Func7Label= NULL;
ui_MasterSoundF8= NULL;
ui_RadiatorF11= NULL;
ui_Func11Label= NULL;
ui_FuncPanelClose= NULL;
ui_FuncCloseLabel= NULL;

}
