// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_Logo;
extern lv_obj_t *ui_WifiLevel;
extern lv_obj_t *ui_WifiLabel;
extern lv_obj_t *ui_layoutPanel;
extern lv_obj_t *ui_OutLoop0;
extern lv_obj_t *ui_OutLoopLabelB;
extern lv_obj_t *ui_OutLoop1;
extern lv_obj_t *ui_OutLoopLabelA;
extern lv_obj_t *ui_TownLoop;
extern lv_obj_t *ui_TownLoopLabel;
extern lv_obj_t *ui_Siding;
extern void ui_event_TurnXCSet( lv_event_t * e);
extern lv_obj_t *ui_TurnXCSet;
extern void ui_event_TurnTL0Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTL0Set;
extern void ui_event_TurnTR0Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTR0Set;
extern void ui_event_TurnTL2Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTL2Set;
extern void ui_event_TurnTR2Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTR2Set;
extern lv_obj_t *ui_SidingLabel;
extern lv_obj_t *ui_ThrPanel;
extern lv_obj_t *ui_ThrComp0;
extern void ui_event_ThrComp0_LocoThr( lv_event_t * e);
extern void ui_event_ThrComp0_LocoName( lv_event_t * e);
extern void ui_event_ThrComp0_LocoRev( lv_event_t * e);
extern void ui_event_ThrComp0_horn( lv_event_t * e);
extern void ui_event_ThrComp0_FuncButton( lv_event_t * e);
extern lv_obj_t *ui_ThrComp1;
extern void ui_event_ThrComp1_LocoThr( lv_event_t * e);
extern void ui_event_ThrComp1_LocoName( lv_event_t * e);
extern void ui_event_ThrComp1_LocoRev( lv_event_t * e);
extern void ui_event_ThrComp1_horn( lv_event_t * e);
extern void ui_event_ThrComp1_FuncButton( lv_event_t * e);
extern lv_obj_t *ui_ThrComp2;
extern void ui_event_ThrComp2_LocoThr( lv_event_t * e);
extern void ui_event_ThrComp2_LocoName( lv_event_t * e);
extern void ui_event_ThrComp2_LocoRev( lv_event_t * e);
extern void ui_event_ThrComp2_horn( lv_event_t * e);
extern void ui_event_ThrComp2_FuncButton( lv_event_t * e);
extern void ui_event_RouteBtn( lv_event_t * e);
extern lv_obj_t *ui_RouteBtn;
extern void ui_event_RouteBtnLabel( lv_event_t * e);
extern lv_obj_t *ui_RouteBtnLabel;
extern void ui_event_ResetEsp( lv_event_t * e);
extern lv_obj_t *ui_ResetEsp;
extern void ui_event_ResetLabel( lv_event_t * e);
extern lv_obj_t *ui_ResetLabel;
extern void ui_event_PowerOff( lv_event_t * e);
extern lv_obj_t *ui_PowerOff;
extern void ui_event_PowerOffLabel( lv_event_t * e);
extern lv_obj_t *ui_PowerOffLabel;
extern lv_obj_t *ui_funcPanel;
extern void ui_event_HeadLightF0( lv_event_t * e);
extern lv_obj_t *ui_HeadLightF0;
extern lv_obj_t *ui_Func2Label;
extern void ui_event_CouplerF3( lv_event_t * e);
extern lv_obj_t *ui_CouplerF3;
extern lv_obj_t *ui_Func3Label;
extern void ui_event_FlangeF7( lv_event_t * e);
extern lv_obj_t *ui_FlangeF7;
extern lv_obj_t *ui_Func7Label;
extern void ui_event_MasterSoundF8( lv_event_t * e);
extern lv_obj_t *ui_MasterSoundF8;
extern void ui_event_RadiatorF11( lv_event_t * e);
extern lv_obj_t *ui_RadiatorF11;
extern lv_obj_t *ui_Func11Label;
extern void ui_event_FuncPanelClose( lv_event_t * e);
extern lv_obj_t *ui_FuncPanelClose;
extern lv_obj_t *ui_FuncCloseLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

