// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_Logo;
extern lv_obj_t *ui_MainTitle;
extern lv_obj_t *ui_WifiLevel;
extern lv_obj_t *ui_WifiLabel;
extern lv_obj_t *ui_layoutPanel;
extern lv_obj_t *ui_Block9;
extern lv_obj_t *ui_SidingLabel;
extern lv_obj_t *ui_Block0;
extern lv_obj_t *ui_TownLoopLabel;
extern lv_obj_t *ui_Block3;
extern lv_obj_t *ui_OutLoopLabelA;
extern lv_obj_t *ui_Block6;
extern lv_obj_t *ui_OutLoopLabelB;
extern lv_obj_t *ui_blk1Container;
extern lv_obj_t *ui_Blk1P0;
extern lv_obj_t *ui_Blk1P1;
extern lv_obj_t *ui_Blk1P2;
extern lv_obj_t *ui_blk2Container;
extern lv_obj_t *ui_Blk2P0;
extern lv_obj_t *ui_Blk2P1;
extern lv_obj_t *ui_Blk2P2;
extern lv_obj_t *ui_blk4Container;
extern lv_obj_t *ui_Blk4P0;
extern lv_obj_t *ui_Blk4P1;
extern lv_obj_t *ui_Blk4P2;
extern lv_obj_t *ui_blk5Container;
extern lv_obj_t *ui_Blk5P0;
extern lv_obj_t *ui_Blk5P1;
extern lv_obj_t *ui_Blk5P2;
extern lv_obj_t *ui_blk7Container;
extern lv_obj_t *ui_Blk7P0;
extern lv_obj_t *ui_Blk7P1;
extern lv_obj_t *ui_Blk7P2;
extern lv_obj_t *ui_blk8Container;
extern lv_obj_t *ui_Blk8P0;
extern lv_obj_t *ui_Blk8P1;
extern lv_obj_t *ui_Blk8P2;
extern void ui_event_TurnXCSet( lv_event_t * e);
extern lv_obj_t *ui_TurnXCSet;
extern void ui_event_TurnTL0Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTL0Set;
extern void ui_event_TurnTR0Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTR0Set;
extern void ui_event_TurnTL2Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTL2Set;
extern void ui_event_TurnTR2Set( lv_event_t * e);
extern lv_obj_t *ui_TurnTR2Set;
extern lv_obj_t *ui_SHL0C;
extern lv_obj_t *ui_SHL1TD;
extern lv_obj_t *ui_SHL1TC;
extern lv_obj_t *ui_SHL2C;
extern lv_obj_t *ui_SHL2D;
extern lv_obj_t *ui_SHR0TC;
extern lv_obj_t *ui_SHR0TD;
extern lv_obj_t *ui_SHR1C;
extern lv_obj_t *ui_SHR2TC;
extern lv_obj_t *ui_SHR2TD;
extern lv_obj_t *ui_ThrPanel;
extern lv_obj_t *ui_ThrComp0;
extern lv_obj_t *ui_ThrComp1;
extern lv_obj_t *ui_ThrComp2;
extern void ui_event_ThrComp2_LocoThr( lv_event_t * e);
extern void ui_event_HomePowerOff( lv_event_t * e);
extern lv_obj_t *ui_HomePowerOff;
extern void ui_event_MenuBtn( lv_event_t * e);
extern lv_obj_t *ui_MenuBtn;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_MenuPanel;
extern void ui_event_DccExBtn( lv_event_t * e);
extern lv_obj_t *ui_DccExBtn;
extern void ui_event_LocoIdBtn( lv_event_t * e);
extern lv_obj_t *ui_LocoIdBtn;
extern lv_obj_t *ui_LocoIdLabel;
extern void ui_event_RouteBtn( lv_event_t * e);
extern lv_obj_t *ui_RouteBtn;
extern lv_obj_t *ui_RouteBtnLabel;
extern void ui_event_MenuCloseBtn( lv_event_t * e);
extern lv_obj_t *ui_MenuCloseBtn;
extern lv_obj_t *ui_MenuCloseLabel;
extern lv_obj_t *ui_LocoIdPanel;
extern lv_obj_t *ui_Loco0BlkSel;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Loco1BlkSel;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Loco2BlkSel;
extern lv_obj_t *ui_Label3;
extern void ui_event_LocoIdCloseBtn( lv_event_t * e);
extern lv_obj_t *ui_LocoIdCloseBtn;
extern lv_obj_t *ui_LocoIdCloseLabel;
extern lv_obj_t *ui_LocoBlkSelLabel;
extern lv_obj_t *ui_KeyboardPanel;
extern void ui_event_dccexKeyboard( lv_event_t * e);
extern lv_obj_t *ui_dccexKeyboard;
extern lv_obj_t *ui_dccexCmdText;
extern void ui_event_keyboardClose( lv_event_t * e);
extern lv_obj_t *ui_keyboardClose;
extern lv_obj_t *ui_CloseLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

