// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#ifndef UI_STARTUP_H
#define UI_STARTUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Startup
extern void ui_Startup_screen_init(void);
extern void ui_Startup_screen_destroy(void);
extern lv_obj_t *ui_Startup;
extern lv_obj_t *ui_StartupMsgArea;
extern lv_obj_t *ui_Title;
extern void ui_event_StartupOff( lv_event_t * e);
extern lv_obj_t *ui_StartupOff;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

