// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32_tft_throttle

#include "ui.h"

lv_obj_t *ui_Startup = NULL;lv_obj_t *ui_StartupMsgArea = NULL;lv_obj_t *ui_Title = NULL;lv_obj_t *ui_StartupOff = NULL;
// event funtions
void ui_event_StartupOff( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      powerOff( e );
}
}

// build funtions

void ui_Startup_screen_init(void)
{
ui_Startup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Startup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_Startup, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_Startup_screen_destroy);
lv_obj_set_style_bg_color(ui_Startup, lv_color_hex(0xBFBDBD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Startup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartupMsgArea = lv_textarea_create(ui_Startup);
lv_obj_set_width( ui_StartupMsgArea, 649);
lv_obj_set_height( ui_StartupMsgArea, 318);
lv_obj_set_align( ui_StartupMsgArea, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_StartupMsgArea,1024);
lv_textarea_set_placeholder_text(ui_StartupMsgArea,"Placeholder...");
lv_obj_set_style_bg_color(ui_StartupMsgArea, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartupMsgArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_StartupMsgArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_StartupMsgArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_StartupMsgArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_StartupMsgArea, lv_color_hex(0x030303), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StartupMsgArea, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Title = lv_label_create(ui_Startup);
lv_obj_set_width( ui_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Title, -9 );
lv_obj_set_y( ui_Title, -199 );
lv_obj_set_align( ui_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Title,"vThrottle");
lv_obj_set_style_text_color(ui_Title, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartupOff = lv_imgbtn_create(ui_Startup);
lv_imgbtn_set_src(ui_StartupOff, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_power_btn_png, NULL);
lv_obj_set_width( ui_StartupOff, 40);
lv_obj_set_height( ui_StartupOff, 40);
lv_obj_set_x( ui_StartupOff, 353 );
lv_obj_set_y( ui_StartupOff, 195 );
lv_obj_set_align( ui_StartupOff, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_StartupOff, ui_event_StartupOff, LV_EVENT_ALL, NULL);

}

void ui_Startup_screen_destroy(void)
{
   if (ui_Startup) lv_obj_del(ui_Startup);

// NULL screen variables
ui_Startup= NULL;
ui_StartupMsgArea= NULL;
ui_Title= NULL;
ui_StartupOff= NULL;

}
